import { pathExists, readJSON, writeFile } from "fs-extra";
import { join, dirname, extname, basename } from "path/posix";

import { normalizedGlob, tryReadDir } from "../../tools/fs";

import { Editor } from "../../editor/main";

const scriptsTemplate = `
/**
 * Generated by Zvibe Editor
 */

import {
    loadScene,
    scriptsDictionary,
    scriptAssetsCache,
    _applyScriptsForObject,
    _removeRegisteredScriptInstance,
    _preloadScriptsAssets,
    getScriptSimulationControl,
    setScriptSimulationPaused,
    stepPausedScriptSimulation,
    configureScriptSourceDebugger,
    getScriptSourceDebuggerSnapshot,
    setScriptSourceBreakpoints,
    setScriptSourceCoverage,
    clearScriptSourceDebuggerTrace,
    getScriptSourceCoverage,
    getClothSimulationControl,
    setClothSimulationPaused,
    stepPausedClothSimulation,
    getPhysics2DSimulationControl,
    setPhysics2DSimulationPaused,
    stepPausedPhysics2DSimulation,
    configureNetworking,
    getNetworkingRuntime,
    getSceneNetworkingConfiguration,
    listLight2DProviderTypes,
    listShadowShape2DProviderTypes,
    getLighting2DRuntimeEvidence,
} from "babylonjs-editor-tools";
{{imports}}

export const scriptsMap = {
    {{exports}}
};

export {
    loadScene,
    scriptsDictionary,
    scriptAssetsCache,
    _applyScriptsForObject,
    _removeRegisteredScriptInstance,
    _preloadScriptsAssets,
    getScriptSimulationControl,
    setScriptSimulationPaused,
    stepPausedScriptSimulation,
    configureScriptSourceDebugger,
    getScriptSourceDebuggerSnapshot,
    setScriptSourceBreakpoints,
    setScriptSourceCoverage,
    clearScriptSourceDebuggerTrace,
    getScriptSourceCoverage,
    getClothSimulationControl,
    setClothSimulationPaused,
    stepPausedClothSimulation,
    getPhysics2DSimulationControl,
    setPhysics2DSimulationPaused,
    stepPausedPhysics2DSimulation,
    configureNetworking,
    getNetworkingRuntime,
    getSceneNetworkingConfiguration,
    listLight2DProviderTypes,
    listShadowShape2DProviderTypes,
    getLighting2DRuntimeEvidence,
};
`;

const createUniqueIdentifier = (filepath: string): string => {
	const nameWithoutExt = filepath.replace(extname(filepath), "");
	return nameWithoutExt
		.replace(/[^a-zA-Z0-9_]/g, "_")
		.replace(/^[0-9]/, "_$&")
		.replace(/\//g, "_");
};

interface ICollectedMetadata {
	entityName: string;
	metadata: any;
}

const serializedEntityReadConcurrency = 32;

function isSerializedEntityFile(file: string): boolean {
	const normalized = file.toLowerCase();
	return normalized.endsWith(".json") && !normalized.endsWith(".bjsmeta.json");
}

async function mapWithConcurrency<T>(values: T[], concurrency: number, callback: (value: T) => Promise<void>): Promise<void> {
	let nextIndex = 0;
	const workers = Array.from({ length: Math.min(concurrency, values.length) }, async () => {
		while (nextIndex < values.length) {
			const value = values[nextIndex++];
			await callback(value);
		}
	});
	await Promise.all(workers);
}

export async function handleExportScripts(editor: Editor): Promise<void> {
	if (!editor.state.projectPath) {
		return;
	}

	const projectPath = dirname(editor.state.projectPath);

	const sceneFolders = await normalizedGlob(join(projectPath, "assets/**/*.scene"), {
		nodir: false,
	});

	const scriptsMap: Record<string, string> = {};

	const availableMetadata: ICollectedMetadata[] = [];

	// Check on all scenes in assets
	await Promise.all(
		sceneFolders.map(async (file) => {
			try {
				const config = await readJSON(join(file, "config.json"));
				if (config.metadata) {
					availableMetadata.push({
						entityName: basename(file),
						metadata: config.metadata,
					});
				}
			} catch (e) {
				// Catch silently.
			}

			const [nodesFiles, meshesFiles, lightsFiles, cameraFiles, soundNodeFiles, spriteManagerfiles, spriteMapFiles] = await Promise.all([
				tryReadDir(join(file, "nodes")),
				tryReadDir(join(file, "meshes")),
				tryReadDir(join(file, "lights")),
				tryReadDir(join(file, "cameras")),
				tryReadDir(join(file, "soundNodes")),
				tryReadDir(join(file, "sprite-managers")),
				tryReadDir(join(file, "sprite-maps")),
			]);

			const serializedEntityFiles = [
				...nodesFiles.map((entry) => join("nodes", entry)),
				...meshesFiles.map((entry) => join("meshes", entry)),
				...lightsFiles.map((entry) => join("lights", entry)),
				...cameraFiles.map((entry) => join("cameras", entry)),
				...soundNodeFiles.map((entry) => join("soundNodes", entry)),
				...spriteMapFiles.map((entry) => join("sprite-maps", entry)),
				...spriteManagerfiles.map((entry) => join("sprite-managers", entry)),
			].filter(isSerializedEntityFile);

			await mapWithConcurrency(serializedEntityFiles, serializedEntityReadConcurrency, async (relativePath) => {
				const data = await readJSON(join(file, relativePath), "utf-8");
				if (data.metadata) {
					availableMetadata.push({
						metadata: data.metadata,
						entityName: data.name ?? data.meshes?.[0]?.name,
					});
				}
			});

			await mapWithConcurrency(
				spriteManagerfiles.filter(isSerializedEntityFile).map((entry) => join("sprite-managers", entry)),
				serializedEntityReadConcurrency,
				async (relativePath) => {
					const data = await readJSON(join(file, relativePath), "utf-8");
					data.spriteManager?.sprites.forEach((sprite) => {
						if (sprite.metadata) {
							availableMetadata.push({
								metadata: sprite.metadata,
								entityName: sprite.name,
							});
						}
					});
				}
			);
		})
	);

	// Check on all nodes in current scene
	const entities = [
		...editor.layout.preview.scene.meshes,
		...editor.layout.preview.scene.lights,
		...editor.layout.preview.scene.cameras,
		...editor.layout.preview.scene.transformNodes,
		...editor.layout.preview.scene.particleSystems,
	] as { name: string; metadata?: any }[];

	if (editor.layout.preview.scene.spriteManagers) {
		entities.push(...editor.layout.preview.scene.spriteManagers.map((sm) => sm.sprites).flat());
	}

	entities.forEach((entity) => {
		if (entity.metadata) {
			availableMetadata.push({
				entityName: entity.name,
				metadata: entity.metadata,
			});
		}
	});

	const promises: Promise<void>[] = [];
	availableMetadata.forEach((configuration) => {
		configuration.metadata.scripts?.forEach((script) => {
			promises.push(
				new Promise<void>(async (resolve) => {
					const path = join(projectPath, "src", script.key);
					if (!(await pathExists(path))) {
						editor.layout.selectTab("console");
						editor.layout.console.error(
							`Processing "${configuration.entityName}". Script '${script.key}' doesn't exist or was moved in the project. Please fix the issue before generating scene.`
						);
						return resolve();
					}

					const extension = extname(script.key).toLowerCase();
					scriptsMap[script.key] = `@/${script.key.replace(extension, "")}`;

					resolve();
				})
			);
		});
	});

	await Promise.all(promises);

	const importStatements: string[] = [];
	Object.keys(scriptsMap).forEach((key) => {
		const scriptName = createUniqueIdentifier(key);
		importStatements.push(`import * as ${scriptName} from "./${key.replace(extname(key), "")}";`);
	});
	const importsContent = importStatements.join("\n");

	const exportsContent = Object.keys(scriptsMap)
		.map((key) => {
			const scriptName = createUniqueIdentifier(key);
			return `"${key}": ${scriptName}`;
		})
		.join(",\n\t");

	const finalContent = scriptsTemplate.replace("{{imports}}", importsContent).replace("{{exports}}", exportsContent);

	await writeFile(join(projectPath, "src/scripts.ts"), finalContent, {
		encoding: "utf-8",
	});
}
