
/**
 * Generated by Zvibe Editor
 */

import {
    loadScene,
    scriptsDictionary,
    scriptAssetsCache,
    _applyScriptsForObject,
    _removeRegisteredScriptInstance,
    _preloadScriptsAssets,
    getScriptSimulationControl,
    setScriptSimulationPaused,
    stepPausedScriptSimulation,
    configureScriptSourceDebugger,
    getScriptSourceDebuggerSnapshot,
    setScriptSourceBreakpoints,
    setScriptSourceCoverage,
    clearScriptSourceDebuggerTrace,
    getScriptSourceCoverage,
    getClothSimulationControl,
    setClothSimulationPaused,
    stepPausedClothSimulation,
    getPhysics2DSimulationControl,
    setPhysics2DSimulationPaused,
    stepPausedPhysics2DSimulation,
    configureNetworking,
    getNetworkingRuntime,
    getSceneNetworkingConfiguration,
    listLight2DProviderTypes,
    listShadowShape2DProviderTypes,
    getLighting2DRuntimeEvidence,
} from "babylonjs-editor-tools";
import * as scripts_game_manager from "./scripts/game-manager";
import * as scripts_spinner from "./scripts/spinner";
import * as scripts_player_controller from "./scripts/player-controller";
import * as scripts_follow_camera from "./scripts/follow-camera";

export const scriptsMap = {
    "scripts/game-manager.ts": scripts_game_manager,
	"scripts/spinner.ts": scripts_spinner,
	"scripts/player-controller.ts": scripts_player_controller,
	"scripts/follow-camera.ts": scripts_follow_camera
};

export {
    loadScene,
    scriptsDictionary,
    scriptAssetsCache,
    _applyScriptsForObject,
    _removeRegisteredScriptInstance,
    _preloadScriptsAssets,
    getScriptSimulationControl,
    setScriptSimulationPaused,
    stepPausedScriptSimulation,
    configureScriptSourceDebugger,
    getScriptSourceDebuggerSnapshot,
    setScriptSourceBreakpoints,
    setScriptSourceCoverage,
    clearScriptSourceDebuggerTrace,
    getScriptSourceCoverage,
    getClothSimulationControl,
    setClothSimulationPaused,
    stepPausedClothSimulation,
    getPhysics2DSimulationControl,
    setPhysics2DSimulationPaused,
    stepPausedPhysics2DSimulation,
    configureNetworking,
    getNetworkingRuntime,
    getSceneNetworkingConfiguration,
    listLight2DProviderTypes,
    listShadowShape2DProviderTypes,
    getLighting2DRuntimeEvidence,
};
