import { dirname, isAbsolute, join, normalize } from "path/posix";
import { ensureDir, pathExists, readFile, readJSON, readdir, stat, writeFile, writeJSON } from "fs-extra";

import { Scene, Tools } from "babylonjs";
import { normalizeModelImporterPlatform } from "babylonjs-editor-tools";

import { getProjectAssetsRootUrl } from "../../project/configuration";
import { exportProject } from "../../project/export/export";
import { execNodePty } from "../../tools/node-pty";

import { IMCPActionOptions } from "../action";

const defaultOptions = {
	optimize: true,
	mergeDecals: false,
	mergeGeometries: false,
	uploadToS3: false,
};

export function getGenerateOptions(): any {
	return { options: defaultOptions };
}

function getBuildProfiles(scene: Scene): any[] {
	scene.metadata ??= {};
	return (scene.metadata.babylonEditorBuildProfiles ??= []);
}
function getBuildReports(scene: Scene): any[] {
	scene.metadata ??= {};
	return (scene.metadata.babylonEditorBuildReports ??= []);
}
function findBuildProfile(scene: Scene, data: any): any {
	const profile = getBuildProfiles(scene).find((item) => item.name === data.name);
	if (!profile) throw new Error(`Build profile "${data.name}" was not found.`);
	return profile;
}

function getProjectOutputPath(projectPath: string, requestedPath: unknown, label: string): { directory: string; outputPath: string; relativePath: string } {
	if (typeof requestedPath !== "string" || !requestedPath.trim()) throw new Error(`${label} must be a non-empty project-relative path.`);
	const directory = dirname(projectPath);
	const outputPath = normalize(isAbsolute(requestedPath) ? requestedPath : join(directory, requestedPath));
	if (outputPath !== directory && !outputPath.startsWith(`${directory}/`)) throw new Error(`${label} must stay inside the project.`);
	return { directory, outputPath, relativePath: outputPath.slice(directory.length + 1) };
}

function getPwaStartUrl(profile: any): string {
	const startUrl = profile.settings?.pwa?.startUrl ?? profile.settings?.web?.basePath ?? "/";
	if (typeof startUrl !== "string" || !startUrl.trim()) throw new Error("PWA startUrl must be a non-empty same-origin URL path.");
	if (!startUrl.startsWith("/")) throw new Error("PWA startUrl must begin with '/'.");
	return startUrl.trim();
}

function createPwaServiceWorkerSource(profile: any): { source: string; cacheName: string; precacheUrls: string[]; startUrl: string } {
	const settings = profile.settings ?? {};
	const pwa = settings.pwa ?? {};
	const startUrl = getPwaStartUrl(profile);
	const precacheUrls = pwa.precacheUrls?.length ? pwa.precacheUrls : [startUrl];
	if (!Array.isArray(precacheUrls) || precacheUrls.some((url) => typeof url !== "string" || !url.trim() || !url.trim().startsWith("/")))
		throw new Error("PWA precacheUrls must be non-empty same-origin URL paths beginning with '/'.");
	const version = typeof settings.version === "string" && settings.version.trim() ? settings.version.trim() : "v1";
	const cacheName = `babylon-editor-pwa-${profile.name}-${version}`.replace(/[^a-zA-Z0-9._-]/g, "-");
	const fallbackUrl = pwa.offlineFallbackUrl ?? startUrl;
	if (typeof fallbackUrl !== "string" || !fallbackUrl.trim() || !fallbackUrl.trim().startsWith("/"))
		throw new Error("PWA offlineFallbackUrl must be a same-origin URL path beginning with '/'.");
	const source = `/* Generated by Babylon.js Editor. Configure this Web profile's PWA cache URLs, then regenerate. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE_URLS = ${JSON.stringify([...new Set(precacheUrls.map((url) => url.trim()))], null, "\t")};
const OFFLINE_FALLBACK_URL = ${JSON.stringify(fallbackUrl.trim())};

self.addEventListener("install", (event) => {
	event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
	event.waitUntil(
		caches.keys().then((keys) => Promise.all(keys.filter((key) => key.startsWith("babylon-editor-pwa-") && key !== CACHE_NAME).map((key) => caches.delete(key)))).then(() => self.clients.claim())
	);
});

self.addEventListener("fetch", (event) => {
	if (event.request.method !== "GET") return;
	event.respondWith(
		caches.match(event.request).then((cached) =>
			cached ||
			fetch(event.request)
				.then((response) => {
					if (!response || !response.ok || new URL(event.request.url).origin !== self.location.origin) return response;
					const copy = response.clone();
					void caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
					return response;
				})
				.catch(() => caches.match(OFFLINE_FALLBACK_URL))
		)
	);
});
`;
	return { source, cacheName, precacheUrls: [...new Set(precacheUrls.map((url) => url.trim()))], startUrl };
}

function getPwaServiceWorkerWebPath(serviceWorkerPath: unknown): string {
	if (typeof serviceWorkerPath !== "string" || !serviceWorkerPath.startsWith("public/") || serviceWorkerPath.length === "public/".length)
		throw new Error("PWA serviceWorkerPath must be inside public/ so the generated web build can serve and register it.");
	return `/${serviceWorkerPath.slice("public/".length)}`;
}

function getPwaServiceWorkerRegistrationSnippet(serviceWorkerUrl: string): string {
	return `<!-- Babylon.js Editor PWA service worker: start -->
<script>
if ("serviceWorker" in navigator) {
	window.addEventListener("load", () => navigator.serviceWorker.register(${JSON.stringify(serviceWorkerUrl)}));
}
</script>
<!-- Babylon.js Editor PWA service worker: end -->`;
}

function getBuildEnvironment(profile: any, projectDirectory: string): Record<string, string> {
	const settings = profile.settings ?? {};
	const environment: Record<string, string> = {
		BJS_EDITOR_BUILD_PROFILE: profile.name,
		BJS_EDITOR_BUILD_TARGET: profile.target,
		BJS_EDITOR_BUILD_PROJECT_DIRECTORY: projectDirectory,
		BJS_EDITOR_BUILD_SETTINGS: JSON.stringify(settings),
	};
	if (typeof settings.productName === "string" && settings.productName.trim()) environment.BJS_EDITOR_PRODUCT_NAME = settings.productName.trim();
	if (typeof settings.version === "string" && settings.version.trim()) environment.BJS_EDITOR_PRODUCT_VERSION = settings.version.trim();
	if (typeof settings.outputDirectory === "string" && settings.outputDirectory.trim()) environment.BJS_EDITOR_OUTPUT_DIRECTORY = settings.outputDirectory.trim();
	if (typeof settings.electronPlatform === "string") environment.BJS_EDITOR_ELECTRON_PLATFORM = settings.electronPlatform;
	if (typeof settings.electronArch === "string") environment.BJS_EDITOR_ELECTRON_ARCH = settings.electronArch;
	if (typeof settings.electronAsar === "boolean") environment.BJS_EDITOR_ELECTRON_ASAR = String(settings.electronAsar);
	if (typeof settings.electronIcon === "string" && settings.electronIcon.trim()) environment.BJS_EDITOR_ELECTRON_ICON = settings.electronIcon.trim();
	return environment;
}
async function getBuildProfileValidation(scene: Scene, data: any, options: IMCPActionOptions): Promise<any> {
	const profile = findBuildProfile(scene, data);
	const projectPath = options.editor.state.projectPath;
	if (!projectPath) throw new Error("No project is currently open.");
	const packagePath = join(dirname(projectPath), "package.json");
	if (!(await pathExists(packagePath)))
		return { profile: structuredClone(profile), valid: false, reasons: ["package.json is missing from the project root."], warnings: [], commands: [] };
	const packageJson = await readJSON(packagePath);
	const scripts = packageJson.scripts ?? {};
	const requiredScripts =
		profile.target === "electron"
			? ["build", "package"]
			: profile.target === "headless"
				? ["build:headless"]
				: profile.target === "android"
					? ["build:android"]
					: profile.target === "ios"
						? ["build:ios"]
						: ["build"];
	const missingScripts = requiredScripts.filter((name) => typeof scripts[name] !== "string");
	const packageManager = options.editor.state.packageManager ?? "yarn";
	const command = (script: string): string => `${packageManager === "bun" ? "bun run" : `${packageManager} run`} ${script}`;
	const settings = profile.settings ?? {};
	const settingReasons: string[] = [];
	const warnings: string[] = [];
	if (settings.version !== undefined && (typeof settings.version !== "string" || !settings.version.trim()))
		settingReasons.push('Build profile setting "version" must be a non-empty string.');
	if (settings.productName !== undefined && (typeof settings.productName !== "string" || !settings.productName.trim()))
		settingReasons.push('Build profile setting "productName" must be a non-empty string.');
	if (settings.signing !== undefined) warnings.push("Code signing settings are persisted but are not yet applied by the build pipeline.");
	if (!settings.outputDirectory) warnings.push("No explicit outputDirectory is configured; the project build script chooses its own output location.");
	if (profile.target === "electron" && settings.electronPlatform !== undefined && !["darwin", "win32", "linux"].includes(settings.electronPlatform))
		settingReasons.push('Electron platform must be "darwin", "win32", or "linux".');
	if (profile.target === "electron" && settings.electronArch !== undefined && !["x64", "arm64"].includes(settings.electronArch))
		settingReasons.push('Electron architecture must be "x64" or "arm64".');
	const reasons = [...missingScripts.map((script) => `The ${profile.target} target requires a package.json \"${script}\" script.`), ...settingReasons];
	return {
		profile: structuredClone(profile),
		valid: reasons.length === 0,
		reasons,
		warnings,
		packageManager,
		commands: missingScripts.length ? [] : requiredScripts.map(command),
	};
}
/** Lists persisted build/export profiles. */
export function listBuildProfiles(scene: Scene): any {
	return { profiles: structuredClone(getBuildProfiles(scene)) };
}
/** Lists the latest persisted export/build reports for this scene. */
export function listBuildReports(scene: Scene): any {
	return { reports: structuredClone(getBuildReports(scene)) };
}

/** Stores one completed export/build report in scene metadata, retaining the newest 20 reports. */
export function recordBuildReport(scene: Scene, data: any): any {
	const report = { id: Tools.RandomId(), createdAt: new Date().toISOString(), ...structuredClone(data) };
	getBuildReports(scene).unshift(report);
	getBuildReports(scene).splice(20);
	return structuredClone(report);
}
/** Creates a named export preset. */
export function createBuildProfile(scene: Scene, data: any): any {
	if (getBuildProfiles(scene).some((item) => item.name === data.name)) throw new Error(`Build profile "${data.name}" already exists.`);
	const profile = { name: data.name, target: data.target ?? "web", options: { ...defaultOptions, ...(data.options ?? {}) }, settings: structuredClone(data.settings ?? {}) };
	getBuildProfiles(scene).push(profile);
	return structuredClone(profile);
}
/** Updates a persisted build profile's target, export options, or target settings. */
export function setBuildProfile(scene: Scene, data: any): any {
	const profile = findBuildProfile(scene, data);
	if (data.target !== undefined) profile.target = data.target;
	if (data.options !== undefined) profile.options = { ...profile.options, ...data.options };
	if (data.settings !== undefined) profile.settings = structuredClone(data.settings);
	return structuredClone(profile);
}

/** Gets the non-secret environment variables injected into this profile's build scripts. */
export function getBuildProfileEnvironment(scene: Scene, data: any, options: IMCPActionOptions): any {
	const projectPath = options.editor.state.projectPath;
	if (!projectPath) throw new Error("No project is currently open.");
	const profile = findBuildProfile(scene, data);
	return { profile: profile.name, target: profile.target, environment: getBuildEnvironment(profile, dirname(projectPath)) };
}

/** Generates a standards-compatible web manifest from one persisted Web build profile's PWA settings. */
export async function generatePwaManifest(scene: Scene, data: any, options: IMCPActionOptions): Promise<any> {
	const profile = findBuildProfile(scene, data);
	if (profile.target !== "web") throw new Error("PWA manifests can only be generated from a Web build profile.");
	const projectPath = options.editor.state.projectPath;
	if (!projectPath) throw new Error("No project is currently open.");
	const settings = profile.settings ?? {};
	const pwa = settings.pwa ?? {};
	const output = getProjectOutputPath(projectPath, pwa.manifestPath ?? "public/manifest.webmanifest", "PWA manifestPath");
	const name = pwa.name ?? settings.productName ?? profile.name;
	const shortName = pwa.shortName ?? name;
	if (typeof name !== "string" || !name.trim() || typeof shortName !== "string" || !shortName.trim()) throw new Error("PWA name and shortName must be non-empty strings.");
	const display = pwa.display ?? "standalone";
	if (!["fullscreen", "standalone", "minimal-ui", "browser"].includes(display)) throw new Error("PWA display must be fullscreen, standalone, minimal-ui, or browser.");
	const manifest = {
		name: name.trim(),
		short_name: shortName.trim(),
		start_url: getPwaStartUrl(profile),
		display,
		background_color: pwa.backgroundColor ?? "#000000",
		theme_color: pwa.themeColor ?? "#000000",
		...(Array.isArray(pwa.icons) ? { icons: pwa.icons } : {}),
	};
	await ensureDir(dirname(output.outputPath));
	await writeJSON(output.outputPath, manifest, { spaces: "\t" });
	return { profile: profile.name, path: output.relativePath, manifest };
}

/** Generates a cache-first, offline-fallback service worker from one Web build profile's persisted PWA settings. */
export async function generatePwaServiceWorker(scene: Scene, data: any, options: IMCPActionOptions): Promise<any> {
	const profile = findBuildProfile(scene, data);
	if (profile.target !== "web") throw new Error("PWA service workers can only be generated from a Web build profile.");
	const projectPath = options.editor.state.projectPath;
	if (!projectPath) throw new Error("No project is currently open.");
	const serviceWorkerPath = profile.settings?.pwa?.serviceWorkerPath ?? "public/sw.js";
	const output = getProjectOutputPath(projectPath, serviceWorkerPath, "PWA serviceWorkerPath");
	const serviceWorkerUrl = getPwaServiceWorkerWebPath(serviceWorkerPath);
	const worker = createPwaServiceWorkerSource(profile);
	await ensureDir(dirname(output.outputPath));
	await writeFile(output.outputPath, worker.source, "utf8");
	return {
		profile: profile.name,
		path: output.relativePath,
		cacheName: worker.cacheName,
		precacheUrls: worker.precacheUrls,
		registration: `navigator.serviceWorker.register(${JSON.stringify(serviceWorkerUrl)});`,
	};
}

/** Installs or updates an idempotent service-worker registration snippet in a standard root index.html web project. */
export async function installPwaServiceWorkerRegistration(scene: Scene, data: any, options: IMCPActionOptions): Promise<any> {
	const profile = findBuildProfile(scene, data);
	if (profile.target !== "web") throw new Error("PWA service-worker registration can only be installed for a Web build profile.");
	const projectPath = options.editor.state.projectPath;
	if (!projectPath) throw new Error("No project is currently open.");
	const serviceWorkerPath = profile.settings?.pwa?.serviceWorkerPath ?? "public/sw.js";
	const output = getProjectOutputPath(projectPath, serviceWorkerPath, "PWA serviceWorkerPath");
	const serviceWorkerUrl = getPwaServiceWorkerWebPath(serviceWorkerPath);
	if (!(await pathExists(output.outputPath))) throw new Error(`PWA service worker not found at ${output.relativePath}. Generate it before installing registration.`);
	const indexPath = join(output.directory, "index.html");
	if (!(await pathExists(indexPath))) throw new Error("No root index.html was found. Register the generated service worker from this framework's web entry point instead.");
	const html = await readFile(indexPath, "utf8");
	const startMarker = "<!-- Babylon.js Editor PWA service worker: start -->";
	const endMarker = "<!-- Babylon.js Editor PWA service worker: end -->";
	const start = html.indexOf(startMarker);
	const end = html.indexOf(endMarker);
	if ((start === -1) !== (end === -1)) throw new Error("The existing PWA registration markers are incomplete. Restore or remove both markers before installing registration.");
	const snippet = getPwaServiceWorkerRegistrationSnippet(serviceWorkerUrl);
	let updated: string;
	if (start !== -1 && end !== -1) {
		updated = `${html.slice(0, start)}${snippet}${html.slice(end + endMarker.length)}`;
	} else {
		const bodyEnd = html.toLowerCase().lastIndexOf("</body>");
		if (bodyEnd === -1) throw new Error("Root index.html has no closing </body> tag. Register the generated worker manually from the web entry point.");
		updated = `${html.slice(0, bodyEnd)}\n\t${snippet}\n${html.slice(bodyEnd)}`;
	}
	const changed = updated !== html;
	if (changed) await writeFile(indexPath, updated, "utf8");
	return { profile: profile.name, path: "index.html", serviceWorkerUrl, changed };
}
/** Deletes a persisted export profile without touching generated output. */
export function deleteBuildProfile(scene: Scene, data: any): any {
	const profiles = getBuildProfiles(scene);
	const index = profiles.findIndex((item) => item.name === data.name);
	if (index === -1) throw new Error(`Build profile "${data.name}" was not found.`);
	profiles.splice(index, 1);
	return { deleted: true, name: data.name };
}
/** Runs the existing export pipeline with a named profile's options. */
export async function runBuildProfile(scene: Scene, data: any, options: IMCPActionOptions): Promise<any> {
	let profile: any;
	try {
		profile = findBuildProfile(scene, data);
		const exported = await exportProject(options.editor, {
			...profile.options,
			modelPlatform: normalizeModelImporterPlatform(profile.target),
			assetPlatform: normalizeModelImporterPlatform(profile.target),
			noDialog: true,
			noProgress: true,
		});
		if (!exported) {
			throw new Error("Project export failed. Check the editor console for details.");
		}
		const report = await getExportReport(scene, data, options);
		return {
			profile: structuredClone(profile),
			...report,
			buildReport: recordBuildReport(scene, { ...report, profile: profile.name, target: profile.target, outcome: "exported" }),
		};
	} catch (error: any) {
		recordBuildReport(scene, { profile: profile?.name ?? data.name, target: profile?.target, outcome: "failed", error: error.message });
		throw error;
	}
}

/** Checks whether the selected target has the scripts required for a full application build. */
export async function validateBuildProfile(scene: Scene, data: any, options: IMCPActionOptions): Promise<any> {
	return getBuildProfileValidation(scene, data, options);
}

/** Exports the active scene, then runs the project's target build scripts in its package-manager environment. */
export async function buildBuildProfile(scene: Scene, data: any, options: IMCPActionOptions): Promise<any> {
	let profile: any;
	let commands: string[] = [];
	try {
		const validation = await getBuildProfileValidation(scene, data, options);
		profile = validation.profile;
		commands = validation.commands;
		if (!validation.valid) throw new Error(`Build profile cannot run: ${validation.reasons.join(" ")}`);
		const exported = await exportProject(options.editor, {
			...profile.options,
			modelPlatform: normalizeModelImporterPlatform(profile.target),
			assetPlatform: normalizeModelImporterPlatform(profile.target),
			noDialog: true,
			noProgress: true,
		});
		if (!exported) {
			throw new Error("Project export failed. Check the editor console for details.");
		}
		const projectPath = options.editor.state.projectPath!;
		const environment = getBuildEnvironment(profile, dirname(projectPath));
		for (const command of commands) {
			const buildProcess = await execNodePty(command, { cwd: dirname(projectPath), env: { ...process.env, ...environment } });
			const exitCode = await buildProcess.wait();
			if (exitCode !== 0) throw new Error(`Target build command failed with code ${exitCode}: ${command}`);
		}
		const report = await getExportReport(scene, data, options);
		return {
			...validation,
			built: true,
			buildEnvironment: environment,
			...report,
			buildReport: recordBuildReport(scene, { ...report, profile: profile.name, target: profile.target, outcome: "built", commands, warnings: validation.warnings }),
		};
	} catch (error: any) {
		recordBuildReport(scene, { profile: profile?.name ?? data.name, target: profile?.target, outcome: "failed", commands, error: error.message });
		throw error;
	}
}

async function getExportOutputStatistics(directory: string): Promise<{ fileCount: number; totalBytes: number; extensions: Record<string, { files: number; bytes: number }> }> {
	const statistics = { fileCount: 0, totalBytes: 0, extensions: {} as Record<string, { files: number; bytes: number }> };
	const visit = async (path: string): Promise<void> => {
		for (const name of await readdir(path)) {
			const child = join(path, name);
			const details = await stat(child);
			if (details.isDirectory()) {
				await visit(child);
				continue;
			}
			statistics.fileCount++;
			statistics.totalBytes += details.size;
			const extension = name.includes(".") ? `.${name.split(".").pop()!.toLowerCase()}` : "[no extension]";
			const entry = (statistics.extensions[extension] ??= { files: 0, bytes: 0 });
			entry.files++;
			entry.bytes += details.size;
		}
	};
	if (await pathExists(directory)) await visit(directory);
	return statistics;
}

export async function getExportReport(scene: Scene, data: any, options: IMCPActionOptions): Promise<any> {
	const projectDirectory = getProjectAssetsRootUrl();
	if (!projectDirectory) {
		throw new Error("No project is currently open.");
	}

	const exportDirectory = join(projectDirectory, "public/scene");
	const exists = await pathExists(exportDirectory);
	const modified = exists ? (await stat(exportDirectory)).mtime.toISOString() : null;
	const output = await getExportOutputStatistics(exportDirectory);

	return {
		profile: data?.name ? structuredClone(findBuildProfile(scene, data)) : null,
		projectPath: options.editor.state.projectPath,
		activeScenePath: options.editor.state.lastOpenedScenePath,
		exportDirectory,
		exists,
		modified,
		output,
	};
}

export async function exportActiveScene(_scene: Scene, data: any, options: IMCPActionOptions): Promise<any> {
	try {
		const exported = await exportProject(options.editor, {
			optimize: data.optimize ?? true,
			noDialog: true,
			noProgress: true,
		});
		if (!exported) {
			throw new Error("Project export failed. Check the editor console for details.");
		}

		const report = await getExportReport(_scene, data, options);
		return { ...report, buildReport: recordBuildReport(_scene, { ...report, outcome: "exported" }) };
	} catch (error: any) {
		recordBuildReport(_scene, { outcome: "failed", error: error.message });
		throw error;
	}
}
