
/**
 * Generated by Zvibe Editor
 */

import {
    loadScene,
    scriptsDictionary,
    scriptAssetsCache,
    _applyScriptsForObject,
    _removeRegisteredScriptInstance,
    _preloadScriptsAssets,
    getScriptSimulationControl,
    setScriptSimulationPaused,
    stepPausedScriptSimulation,
    configureScriptSourceDebugger,
    getScriptSourceDebuggerSnapshot,
    setScriptSourceBreakpoints,
    setScriptSourceCoverage,
    clearScriptSourceDebuggerTrace,
    getScriptSourceCoverage,
    getClothSimulationControl,
    setClothSimulationPaused,
    stepPausedClothSimulation,
    getPhysics2DSimulationControl,
    setPhysics2DSimulationPaused,
    stepPausedPhysics2DSimulation,
    configureNetworking,
    getNetworkingRuntime,
    getSceneNetworkingConfiguration,
    listLight2DProviderTypes,
    listShadowShape2DProviderTypes,
    getLighting2DRuntimeEvidence,
} from "babylonjs-editor-tools";
import * as scripts_box from "./scripts/box";

export const scriptsMap = {
    "scripts/box.ts": scripts_box
};

export {
    loadScene,
    scriptsDictionary,
    scriptAssetsCache,
    _applyScriptsForObject,
    _removeRegisteredScriptInstance,
    _preloadScriptsAssets,
    getScriptSimulationControl,
    setScriptSimulationPaused,
    stepPausedScriptSimulation,
    configureScriptSourceDebugger,
    getScriptSourceDebuggerSnapshot,
    setScriptSourceBreakpoints,
    setScriptSourceCoverage,
    clearScriptSourceDebuggerTrace,
    getScriptSourceCoverage,
    getClothSimulationControl,
    setClothSimulationPaused,
    stepPausedClothSimulation,
    getPhysics2DSimulationControl,
    setPhysics2DSimulationPaused,
    stepPausedPhysics2DSimulation,
    configureNetworking,
    getNetworkingRuntime,
    getSceneNetworkingConfiguration,
    listLight2DProviderTypes,
    listShadowShape2DProviderTypes,
    getLighting2DRuntimeEvidence,
};
