import { createServer } from "http";

import { Scene } from "babylonjs";

import { Editor } from "../editor/main";

import { IMCPActionOptions } from "./action";
import {
	createVisualScriptGraph,
	deleteVisualScriptGraph,
	listVisualScriptGraphs,
	runVisualScriptGraph,
	setVisualScriptGraph,
	setVisualScriptNodePosition,
} from "./visual-scripting/graphs";
import {
	compareVisualRegressionImages,
	createPerformanceBudget,
	createSceneTest,
	deletePerformanceBudget,
	deleteSceneTest,
	listPerformanceBudgets,
	listSceneTests,
	runPerformanceBudgets,
	runSceneTests,
	setPerformanceBudget,
	setSceneTest,
} from "./testing/tests";
import {
	assignAddressableAsset,
	buildAddressableCatalog,
	createAddressableGroup,
	diffAddressableCatalogs,
	findAddressableAssetsByLabels,
	listAddressableGroups,
	removeAddressableAsset,
	setAddressableAssetLabels,
} from "./addressables/addressables";
import {
	createLocalizationTable,
	deleteLocalizationEntry,
	deleteLocalizationTable,
	listLocalizationTables,
	pseudoLocalizeEntry,
	resolveLocalizationEntry,
	setLocalizationEntry,
	validateLocalization,
} from "./localization/localization";
import { createBehaviorTree, deleteBehaviorTree, listBehaviorTrees, runBehaviorTree, setBehaviorTree } from "./ai/behavior-trees";
import { listProjectPackages, modifyProjectPackage } from "./project/packages";
import { applyCollaborativeTextOperations, getCollaborativeTextDocument, rebaseCollaborativeTextDocument } from "./project/collaborative-text";
import { applyCollaborativeOrderedCollectionOperations, getCollaborativeOrderedCollection, rebaseCollaborativeOrderedCollection } from "./project/collaborative-lists";
import {
	abortProjectSourceControlIntegration,
	applyProjectSourceControlTextResolution,
	commitProjectSourceControl,
	continueProjectSourceControlIntegration,
	createProjectSourceControlBranch,
	createProjectSourceControlTag,
	deleteProjectSourceControlBranch,
	deleteProjectSourceControlRemoteBranch,
	deleteProjectSourceControlRemoteTag,
	deleteProjectSourceControlTag,
	fetchProjectSourceControl,
	getProjectSourceControlIntegrationState,
	getProjectSourceControlDiff,
	getProjectSourceControlHistory,
	getProjectSourceControlStatus,
	inspectProjectSourceControlAuthentication,
	inspectProjectSourceControlImageConflict,
	inspectProjectSourceControlRemoteRefs,
	inspectProjectSourceControlConflictDetails,
	listProjectSourceControlRefs,
	pullProjectSourceControl,
	previewProjectSourceControlIntegration,
	publishProjectSourceControlRemoteBranch,
	publishProjectSourceControlRemoteTag,
	pushProjectSourceControl,
	stageProjectSourceControlPaths,
	startProjectSourceControlMerge,
	startProjectSourceControlRebase,
	switchProjectSourceControlBranch,
	unstageProjectSourceControlPaths,
	resolveProjectSourceControlConflict,
} from "./project/source-control";
import {
	createProjectSourceControlReview,
	getProjectSourceControlReview,
	getProjectSourceControlReviewMetadata,
	getProjectSourceControlReviewProvider,
	listProjectSourceControlReviewChecks,
	listProjectSourceControlReviews,
	mergeProjectSourceControlReview,
	rerunProjectSourceControlReviewChecks,
	setProjectSourceControlReviewMetadata,
	setProjectSourceControlReviewProvider,
	submitProjectSourceControlReview,
} from "./project/source-control-reviews";
import { acquireProjectAssetLock, listProjectAssetLocks, refreshProjectAssetLock, releaseProjectAssetLock } from "./project/asset-locks";
import { compareProjectSceneAssets } from "./project/semantic-diff";
import { mergeProjectSceneAssets } from "./project/semantic-merge";
import { createProjectSemanticMergeRule, deleteProjectSemanticMergeRule, listProjectSemanticMergeRules, setProjectSemanticMergeRule } from "./project/semantic-merge-rules";
import { createProjectChangelist, deleteProjectChangelist, listProjectChangelists, setProjectChangelist, setProjectChangelistFiles } from "./project/changelists";
import {
	authorizeProjectCollaborationRequest,
	configureProjectCollaboration,
	createProjectCollaborationMember,
	deleteProjectCollaborationMember,
	getProjectCollaborationStatus,
	heartbeatProjectCollaborationSession,
	joinProjectCollaborationSession,
	leaveProjectCollaborationSession,
	listProjectCollaborationMembers,
	listProjectCollaborationPresence,
	setProjectCollaborationMember,
} from "./project/collaboration";
import { generateRemoteCollaborationTlsCertificate, inspectRemoteCollaborationTlsCertificate } from "./project/collaboration-tls";
import { discoverRemoteCollaborationProjects, getRemoteCollaborationDiscovery, setRemoteCollaborationDiscovery } from "./project/collaboration-discovery";
import { getRemoteCollaborationRelay, reconnectRemoteCollaborationRelay, setRemoteCollaborationRelay } from "./project/collaboration-relay";
import {
	clearRemoteCollaborationEventHistory,
	getRemoteCollaborationGateway,
	getProjectAssetLockFederation,
	initializeRemoteCollaborationGateway,
	listRemoteCollaborationEvents,
	publishRemoteCollaborationOperation,
	setRemoteCollaborationEventHistory,
	setRemoteCollaborationGateway,
} from "./project/remote-collaboration";
import { applyCollaborativeNodeTransform, getCollaborationNodeRevision } from "./project/collaboration-transforms";
import { applyCollaborativeNodeEdit, getCollaborationNodeEditRevision } from "./project/collaboration-node-edits";
import {
	applyCollaborativeHierarchyEdit,
	applyCollaborativeNodeProperties,
	getCollaborationHierarchyRevision,
	getCollaborationNodePropertyRevision,
} from "./project/collaboration-structure";
import { createSortingLayer, listSortingLayers, setNodeSortingLayer } from "./2d/sorting-layers";
import { getXRConfiguration, setXRConfiguration } from "./xr/xr";
import { createCloth, deleteCloth, listCloths, setCloth } from "./cloth/cloth";
import {
	createPhysics2DJoint,
	setPhysics2DJoint,
	createPhysics2DEffector,
	deletePhysics2DEffector,
	createPhysics2DMaterial,
	deletePhysics2DJoint,
	listPhysics2DEffectors,
	deletePhysics2DMaterial,
	listPhysics2D,
	getPhysics2DSettings,
	generatePhysics2DPolygonCollider,
	listPhysics2DJoints,
	listPhysics2DMaterials,
	removePhysics2DBody,
	setPhysics2DBody,
	setPhysics2DSettings,
	setPhysics2DEffector,
	setPhysics2DMaterial,
} from "./physics2d/physics2d";
import {
	createIKController,
	createLookAtConstraint,
	deleteIKController,
	deleteLookAtConstraint,
	deleteSpriteIKController,
	getSkeletonBones,
	listIKControllers,
	listLookAtConstraints,
	listSpriteIKControllers,
	createSpriteIKController,
	createSpriteIKRig,
	bakeSpriteIKAnimation,
	setIKController,
	setLookAtConstraint,
	setSpriteIKController,
} from "./rigging/ik";
import { createRigConstraint, createRigLayer, deleteRigConstraint, deleteRigLayer, listRigLayers, setRigConstraint, setRigLayer } from "./rigging/rig-layers";
import { getRigConstraintGraph, setRigConstraintGraphLayout } from "./rigging/rig-constraint-graph";
import { getMeshSkinWeights, mirrorMeshSkinWeights, optimizeMeshSkinWeights, paintMeshSkinWeights, setMeshSkinWeights } from "./rigging/skin-weights";
import {
	createHumanoidAvatar,
	deleteHumanoidAvatar,
	getHumanoidAvatar,
	getHumanoidMusclePose,
	inspectHumanoidRetarget,
	listHumanoidAvatars,
	retargetHumanoidAnimation,
	setHumanoidAvatar,
	setHumanoidMuscleLimits,
	setHumanoidPosePreview,
	setHumanoidRetargetDebugVisualization,
	stopHumanoidPosePreview,
	validateSceneHumanoidAvatar,
} from "./rigging/humanoid-avatar";
import { createHumanoidAvatarMask, deleteHumanoidAvatarMask, listHumanoidAvatarMasks, setHumanoidAvatarMask } from "./rigging/avatar-masks";

import { getSceneHierarchy } from "./scene/hierarchy";
import {
	createScene,
	createSceneLinkNode,
	deleteScene,
	duplicateScene,
	getActiveScene,
	getSceneSettings,
	get2DSceneMode,
	getPhysicsCollisionLayers,
	listSceneLinks,
	listScenes,
	openScene,
	reloadSceneLink,
	saveScene,
	setSceneSettings,
	set2DSceneMode,
	setPhysicsCollisionLayers,
} from "./scene/scene";

import {
	getNode,
	getNodeClassification,
	setNodeClassification,
	setNodeTransform,
	setNodeProperties,
	setNodeParent,
	renameNode,
	deleteNode,
	selectNode,
	getSelectedNodes,
} from "./nodes/nodes";
import {
	createPrimitiveMesh,
	createInstance,
	cloneMesh,
	createDecal,
	getDecal,
	getMeshCollision,
	getMeshGeometry,
	getMeshVertexData,
	getMeshTopology,
	getMeshSelection,
	getMeshLODs,
	getMeshMorphTargets,
	listSkeletons,
	setDecal,
	setGroundHeightmap,
	getTerrain,
	sculptTerrain,
	carveTerrainHole,
	scatterTerrainInstances,
	paintTerrainDetails,
	setMeshCollision,
	setMeshGeometry,
	setMeshVertexData,
	setMeshSelection,
	setMeshLODs,
	setMeshMaterial,
	setMeshMorphTargets,
	setMeshVisibility,
	flipMeshNormals,
	extrudeMeshFaces,
	insetMeshFaces,
	booleanMesh,
	bevelMeshEdge,
	bevelMeshEdges,
	bridgeMeshEdges,
	setMeshUVProjection,
	unwrapMeshUVs,
	subdivideMesh,
	weldMeshVertices,
	setMeshPhysics,
	setSkeleton,
	getMeshBoundingInfo,
} from "./meshes/meshes";
import {
	addLightToClusteredContainer,
	createClusteredLightContainer,
	createLight,
	createReflectionProbe,
	deleteReflectionProbe,
	getLight,
	listReflectionProbes,
	removeLightFromClusteredContainer,
	removeLightShadows,
	setIblShadows,
	setLightProperties,
	setLightShadows,
	setReflectionProbe,
	listLightingScenarios,
	createLightingScenario,
	applyLightingScenario,
	blendLightingScenario,
	deleteLightingScenario,
} from "./lights/lights";
import { createCamera, getCamera, setActiveCamera, setCameraProperties } from "./cameras/cameras";
import { getCameraPostProcesses, setCameraPostProcess } from "./rendering/post-process";
import { applyRenderingProfile, createRenderingProfile, deleteRenderingProfile, listRenderingProfiles, setRenderingProfile } from "./rendering/profiles";
import { createRenderingVolume, deleteRenderingVolume, evaluateRenderingVolumes, listRenderingVolumes, setRenderingVolume } from "./rendering/volumes";
import {
	createCustomRenderPass,
	deleteCustomRenderPass,
	evaluateCustomRenderPassGraph,
	getCustomRenderPassGraphDiagnostics,
	getCustomRenderPassGpuProfiling,
	getCustomRenderPassGraphSchedule,
	listCustomRenderPasses,
	readCustomComputeStorageBuffer,
	setCustomComputeStorageBufferData,
	setCustomComputeUniformBufferValues,
	setCustomRenderPass,
	setCustomRenderPassGpuProfiling,
} from "./rendering/custom-passes";
import {
	addCustomComputeNode,
	compileCustomComputeNodeGraph,
	connectCustomComputeNodes,
	deleteCustomComputeNode,
	disconnectCustomComputeNodes,
	getCustomComputeNodeGraph,
	initializeCustomComputeNodeGraph,
	setCustomComputeNode,
	setCustomComputeNodeGraph,
} from "./rendering/compute-graph";
import {
	deleteCustomComputeSubgraphInstance,
	deleteCustomComputeSubgraph,
	getCustomComputeSubgraphDiagnostics,
	getCustomComputeSubgraphMigration,
	getCustomComputeSubgraph,
	insertCustomComputeSubgraph,
	listCustomComputeSubgraphInstances,
	listCustomComputeSubgraphs,
	migrateCustomComputeSubgraph,
	refreshCustomComputeSubgraphInstance,
	saveCustomComputeSubgraph,
	setCustomComputeSubgraphInstance,
} from "./rendering/compute-subgraphs";
import { debugCustomComputeNodeGraph, getCustomComputeNodeProfile, previewCustomComputeNodeGraph } from "./rendering/compute-debug";
import { getCustomComputeTextureNodePreviews } from "./rendering/compute-texture-preview";
import { captureCustomRenderPassOutput } from "./rendering/render-output-preview";
import {
	assignTextureToMaterial,
	createMaterial,
	createMaterialVariant,
	getMaterialVariant,
	rebaseMaterialVariant,
	createMaterialPreset,
	deleteMaterialPreset,
	deleteMaterial,
	getNodeMaterialGraph,
	listNodeMaterialCustomBlocks,
	addNodeMaterialCustomBlock,
	deleteNodeMaterialCustomBlock,
	getNodeMaterialBlackboard,
	getNodeMaterialSubgraph,
	getMaterialLightmap,
	listNodeMaterialVariants,
	setNodeMaterialVariant,
	applyNodeMaterialVariant,
	deleteNodeMaterialVariant,
	listMaterials,
	listMaterialTypes,
	replaceNodeMaterialGraph,
	applyNodeMaterialSubgraph,
	saveNodeMaterialSubgraph,
	setEnvironmentTexture,
	setMaterialProperties,
	setMaterialLightmap,
	listMaterialPresets,
	applyMaterialPreset,
	setNodeMaterialInputs,
	setNodeMaterialBlackboard,
	setNodeMaterialBlackboardValues,
	paintTerrainLayer,
	validateNodeMaterialGraph,
	stripNodeMaterialUnusedBlocks,
} from "./materials/materials";
import {
	applyAssetImporterPreset,
	cancelBackgroundAssetIndexing,
	convertImageAsset,
	createAssetFolder,
	deleteAssetImporterPreset,
	deleteAsset,
	getAssetDetails,
	getAssetDependencies,
	getAssetImportStatus,
	getAssetImporter,
	openAssetInspector,
	getAudioImporterResult,
	getVideoImporterResult,
	getFontImporterResult,
	getMaterialImporterResult,
	getModelImporterResult,
	getModelAnimationClips,
	getModelAuthoredLods,
	getModelMaterialRemaps,
	getModelMaterialSearch,
	getModelPlatformOverrides,
	inspectModelMaterialExtraction,
	extractModelMaterials,
	inspectModelTextureExtraction,
	extractModelTextures,
	getModelGeneratedLods,
	getAnimationImporterResult,
	getAnimatorControllerAssetImport,
	importAnimatorControllerAsset,
	getAssetByGuid,
	getAssetPreview,
	getTextureImporterResult,
	getPersistentAssetRegistryStatus,
	getBackgroundAssetIndexingStatus,
	getAssetWatchStatus,
	inspectAssetDependencyDiagnostics,
	inspectAssetDependencyGraph,
	exportAssetDependencyGraph,
	openAssetDependencyGraphView,
	inspectAssetMovePlan,
	applyAssetMovePlan,
	applyTextureImporter,
	applyAudioImporter,
	applyVideoImporter,
	applyFontImporter,
	applyMaterialImporter,
	applyModelImporter,
	setModelMaterialRemaps,
	setModelMaterialSearch,
	setModelPlatformOverrides,
	setModelGeneratedLods,
	setModelAuthoredLods,
	applyAnimationImporter,
	importAsset,
	instantiateMeshAsset,
	listAssetImporterPresets,
	listAssetImportDiagnostics,
	listAssetImporterTypes,
	listDependencyScannerTypes,
	listAssets,
	moveAsset,
	queryPersistentAssetRegistry,
	reimportAsset,
	rebuildAssetDependencyIndex,
	rebuildPersistentAssetRegistry,
	refreshWatchedAssets,
	refreshPersistentAssetRegistryPaths,
	refreshAssetImportStates,
	startBackgroundAssetIndexing,
	setAssetMetadata,
	setAssetOrganization,
	setAssetImporterPreset,
	setAssetImporterSettings,
	setModelAnimationClips,
	setModelRigOptimization,
	validateAssetImporterSettings,
} from "./assets/assets";
import {
	applyVfxBudgetProfile,
	createVfxBudgetProfile,
	deleteVfxBudgetProfile,
	getNodeParticleSystemGraph,
	getParticleAttractors,
	instantiateParticleSystem,
	listNodeParticleSystems,
	listParticleAssets,
	listParticleSystems,
	listVfxBudgetProfiles,
	replaceNodeParticleSystemGraph,
	setParticleSystemPlaying,
	setParticleAttractors,
	setParticleSystemProperties,
	setVfxBudgetProfile,
	validateParticleSystem,
} from "./particles/particles";
import { getParticleEvents, setParticleEvents, triggerParticleEvent } from "./particles/events";
import { getParticleVectorFields, setParticleVectorFields } from "./particles/vector-fields";
import { createParticleTextureVectorField, getParticleTextureVectorFields, setParticleTextureVectorFields } from "./particles/texture-vector-fields";
import { getParticleProximityEvents, setParticleProximityEvents } from "./particles/proximity-events";
import { createVfxTrail, deleteVfxTrail, getVfxTrail, listVfxTrails, setVfxTrail } from "./vfx/trails";
import {
	applyAudioMixerSnapshot,
	assignSoundNodeToAudioBus,
	createAudioBus,
	createAudioMixerSnapshot,
	createSound,
	deleteAudioBus,
	deleteAudioMixerSnapshot,
	getSound,
	listAudioBuses,
	listAudioRuntimeDiagnostics,
	listAudioMixerSnapshots,
	listSoundAssets,
	setAudioBus,
	setSoundPlaying,
	setSoundProperties,
} from "./sounds/sounds";
import { controlVideoPlayer, createVideoPlayer, deleteVideoPlayer, listVideoPlayers, setVideoPlayer } from "./videos/videos";
import {
	createAnimation,
	deleteAnimationGroup,
	exportAnimationGroup,
	editAnimationWindowKeys,
	getAnimationGroup,
	getAnimationWindow,
	importAnimationGroup,
	listAnimationEvents,
	listAnimationGroups,
	playAnimationGroup,
	openAnimationWindow,
	setAnimationEvents,
	setAnimationCurveKeys,
	setAnimationCurveComponentKeys,
	setAnimationCurveTangents,
	autoSmoothAnimationCurveTangents,
	setAnimationKeys,
	sampleAnimationCurve,
	stopAnimationGroup,
} from "./animations/animations";
import { openMarketplaceAndSelectAsset, openMarketplaceAndSearch, downloadMarketplaceAsset } from "./marketplace/marketplace";
import {
	attachScript,
	createScript,
	deleteScript,
	detachScript,
	getScriptExportedFields,
	getScriptRuntimeDiagnostics,
	getScriptSemanticDiagnostics,
	getProjectScriptSemanticDiagnostics,
	listAttachedScripts,
	listScriptTemplates,
	listCustomScriptTemplates,
	setCustomScriptTemplate,
	listScripts,
	readScript,
	renameScript,
	setScriptExportedValue,
	setAttachedScriptExecutionOrder,
	listProjectScriptExecutionOrders,
	setProjectScriptExecutionOrder,
	listProjectWideScriptExecutionOrders,
	setProjectWideScriptExecutionOrder,
	validateScript,
	writeScript,
} from "./scripts/scripts";
import { writeAgentScript, runAgentScript, listAgentScripts, getEditorApi } from "./scripts/editor-scripts";
import { captureVisualRegressionBaseline, getScreenshot, focusNode, runProject } from "./screenshot";
import { createBatchHandler } from "./batch";
import {
	captureProfilerSnapshot,
	deleteProfilerCapture,
	getProfilerCapture,
	compareProfilerSnapshots,
	getEditorCapabilities,
	getDeviceSimulation,
	getEditorStatus,
	getSceneDiagnostics,
	listProfilerSnapshots,
	listProfilerCaptures,
	redoEditor,
	setPreviewPlayMode,
	setDeviceSimulation,
	startProfilerCapture,
	stopProfilerCapture,
	undoEditor,
} from "./editor";
import { clearEditorConsole, getGizmoSettings, listEditorTabs, runEditorTerminalCommand, selectEditorTab, setGizmoSettings, writeEditorConsole } from "./editor-controls";
import {
	generatePwaManifest,
	generatePwaServiceWorker,
	installPwaServiceWorkerRegistration,
	buildBuildProfile,
	createBuildProfile,
	setBuildProfile,
	deleteBuildProfile,
	exportActiveScene,
	getExportReport,
	getBuildProfileEnvironment,
	getGenerateOptions,
	listBuildProfiles,
	listBuildReports,
	runBuildProfile,
	validateBuildProfile,
} from "./project/export";
import {
	createSprite,
	createSpriteManager,
	createSpriteMap,
	createAnimatedTile,
	clearTileColliderGenerator,
	deleteAnimatedTile,
	generateTileColliders,
	refreshTileColliders,
	getTileColliderGenerator,
	listAnimatedTiles,
	createTilePalette,
	deleteTilePalette,
	listTilePalettes,
	listSpriteManagers,
	listSpriteMaps,
	listSprites,
	playSpriteAnimation,
	setSprite,
	setSpriteManager,
	setSpriteMap,
	setSpriteMapRuleTiles,
	resolveSpriteMapRuleTiles,
	setSpriteMapTiles,
	setAnimatedTile,
	setTilePalette,
	paintTilePalette,
	packSpriteAtlas,
	sliceSpriteSheet,
} from "./sprites/sprites";
import { createGUIAsset, getGUIAsset, getGUIContent, instantiateGUIAsset, listGUIs, saveGUIAsset, setGUIContent, validateGUIAccessibility } from "./gui/gui";
import { createCinematic, getCinematic, listCinematics, playCinematic, saveCinematic } from "./cinematic/cinematic";
import {
	computeNavMeshPath,
	createNavAgent,
	createNavMesh,
	deleteNavAgent,
	listNavMeshLinks,
	listNavMeshAreas,
	createNavMeshLink,
	setNavMeshLink,
	setNavMeshAreas,
	deleteNavMeshLink,
	startNavAgent,
	stopNavAgent,
	getNavMesh,
	getNavMeshData,
	listNavAgents,
	listNavMeshes,
	rebuildNavMesh,
	setNavAgentDestination,
	setNavAgent,
	setNavMeshConfiguration,
} from "./navmesh/navmesh";
import { getRagdoll, listRagdolls, saveRagdoll } from "./ragdoll/ragdoll";
import { getProjectPreferences, listInstalledExternalEditors, listProjectTemplates, openProjectFileInExternalEditor, setProjectPreferences } from "./project/project";
import {
	applyPrefabInstanceBoundary,
	applyPrefabInstanceNode,
	applyPrefabInstanceRoot,
	createPrefab,
	createPrefabVariant,
	getPrefab,
	inspectPrefabAssetNodeProperty,
	inspectPrefabInstanceLinks,
	inspectPrefabInstanceStructure,
	capturePrefabInstanceStructure,
	comparePrefabInstances,
	inspectPrefabVariantStructure,
	inspectPrefabVariantComponents,
	inspectPrefabVariantRebase,
	instantiatePrefab,
	listPrefabs,
	promotePrefabInstanceBoundaryOverrides,
	rebasePrefabVariant,
	revertPrefabInstanceBoundary,
	revertPrefabInstanceNode,
	revertPrefabInstanceRoot,
	setPrefabAssetNodeProperties,
	setPrefabAssetNodeProperty,
	setPrefabVariantOverrides,
	setPrefabVariantStructure,
	setPrefabVariantComponents,
	unpackPrefabInstance,
} from "./prefabs/prefabs";
import {
	createAnimatorController,
	deleteAnimatorController,
	deleteAnimatorSubgraph,
	getAnimatorCompiledGraph,
	getAnimatorRuntimeDebug,
	getAnimatorController,
	listAnimatorControllers,
	openAnimatorRuntimeDebugger,
	resetAnimatorTrigger,
	setAnimatorBlendTree,
	setAnimatorController,
	setAnimatorEntryState,
	setAnimatorEntryTransitions,
	setAnimatorLayer,
	setAnimatorLayerBlending,
	setAnimatorLayerIKPass,
	setAnimatorSynchronizedLayerOverrides,
	setAnimatorLayerState,
	setAnimatorParameter,
	setAnimatorParameterDefinition,
	setAnimatorRootMotion,
	setAnimatorStateAvatarMask,
	setAnimatorStateBehaviours,
	setAnimatorStateMask,
	setAnimatorStateGraphPosition,
	setAnimatorState,
	setAnimatorSubgraph,
	setAnimatorSubStateMachine,
	setAnimatorTransition,
	setAnimatorTrigger,
} from "./animator/animator";
import {
	createSpline,
	deleteSplineFollower,
	evaluateSpline,
	getSpline,
	instantiateSplineAsset,
	listSplineAssets,
	listSplineFollowers,
	listSplines,
	projectSplineToTerrain,
	saveSplineAsset,
	setSpline,
	setSplineFollower,
} from "./splines/splines";
import {
	createInputActionMap,
	deleteInputActionMap,
	generateInputActionWrapper,
	listInputActionMaps,
	setInputActionBinding,
	setInputActionMap,
	simulateInputTouch,
} from "./input/input";
import { createPhysicsConstraint, deletePhysicsConstraint, getPhysicsSimulationState, listPhysicsConstraints, validatePhysicsScene } from "./physics/constraints";
import { createVehicle, deleteVehicle, listVehicles, setVehicle, setVehicleInput, setVehicleWheels } from "./physics/vehicles";
import {
	clearPhysicsContactCapture,
	getPhysicsContactCapture,
	getPhysicsContactVisualization,
	setPhysicsContactVisualization,
	startPhysicsContactCapture,
	stopPhysicsContactCapture,
} from "./physics/contacts";
import { getPhysicsSimulationControl, setPhysicsSimulationPaused, stepPhysicsSimulation } from "./physics/simulation";
import {
	activateHighestPriorityVirtualCamera,
	activateVirtualCamera,
	blendVirtualCamera,
	createVirtualCamera,
	deleteCameraTargetGroup,
	deleteVirtualCamera,
	listCameraTargetGroups,
	listVirtualCameras,
	setCameraTargetGroup,
	setVirtualCameraDolly,
	setVirtualCameraTargetGroups,
} from "./virtual-cameras/virtual-cameras";
import { deleteCameraImpulseSource, fireCameraImpulse, listCameraImpulseSources, setCameraImpulseSource } from "./virtual-cameras/impulses";
import { deleteTerrainStreamingGroup, listTerrainStreamingGroups, setTerrainStreamingGroup } from "./terrain/streaming";
import { getParticleCollisionPlanes, getParticleCollisionSpheres, setParticleCollisionPlanes, setParticleCollisionSpheres } from "./particles/collisions";

export interface IEditorMCPDataType {
	endpoint: string;
	[index: string]: any;
}

/**
 * The port the editor MCP HTTP server listens on.
 */
export const MCPServerPort = 3712;

/**
 * Map of all the MCP endpoints to their handler.
 * Each handler has the signature `(scene, data, options) => any | Promise<any>`.
 */
export const MCPEndpoints: Record<string, (scene: Scene, data: any, options: IMCPActionOptions) => any> = {
	// Editor state & control
	get_editor_status: getEditorStatus,
	get_editor_capabilities: getEditorCapabilities,
	get_device_simulation: getDeviceSimulation,
	set_device_simulation: setDeviceSimulation,
	get_scene_diagnostics: getSceneDiagnostics,
	list_profiler_snapshots: listProfilerSnapshots,
	capture_profiler_snapshot: captureProfilerSnapshot,
	compare_profiler_snapshots: compareProfilerSnapshots,
	list_profiler_captures: listProfilerCaptures,
	get_profiler_capture: getProfilerCapture,
	start_profiler_capture: startProfilerCapture,
	stop_profiler_capture: stopProfilerCapture,
	delete_profiler_capture: deleteProfilerCapture,
	undo_editor: undoEditor,
	redo_editor: redoEditor,
	set_preview_play_mode: setPreviewPlayMode,

	// Scene & project
	get_scene_hierarchy: (scene, data) => getSceneHierarchy(scene, data.rootNodeName),
	list_scenes: listScenes,
	create_scene: createScene,
	open_scene: openScene,
	duplicate_scene: duplicateScene,
	delete_scene: deleteScene,
	list_scene_links: listSceneLinks,
	create_scene_link: createSceneLinkNode,
	reload_scene_link: reloadSceneLink,
	get_active_scene: getActiveScene,
	save_scene: saveScene,
	get_scene_settings: getSceneSettings,
	set_scene_settings: setSceneSettings,
	get_2d_scene_mode: get2DSceneMode,
	set_2d_scene_mode: set2DSceneMode,
	get_physics_collision_layers: getPhysicsCollisionLayers,
	set_physics_collision_layers: setPhysicsCollisionLayers,
	get_collaborative_text_document: getCollaborativeTextDocument,
	apply_collaborative_text_operations: applyCollaborativeTextOperations,
	rebase_collaborative_text_document: rebaseCollaborativeTextDocument,
	get_collaborative_ordered_collection: getCollaborativeOrderedCollection,
	apply_collaborative_ordered_collection_operations: applyCollaborativeOrderedCollectionOperations,
	rebase_collaborative_ordered_collection: rebaseCollaborativeOrderedCollection,

	// Node generic operations
	get_node: getNode,
	get_node_classification: getNodeClassification,
	set_node_classification: setNodeClassification,
	set_node_transform: setNodeTransform,
	get_collaboration_node_revision: getCollaborationNodeRevision,
	apply_collaborative_node_transform: applyCollaborativeNodeTransform,
	get_collaboration_node_edit_revision: getCollaborationNodeEditRevision,
	apply_collaborative_node_edit: applyCollaborativeNodeEdit,
	get_collaboration_hierarchy_revision: getCollaborationHierarchyRevision,
	apply_collaborative_hierarchy_edit: applyCollaborativeHierarchyEdit,
	get_collaboration_node_property_revision: getCollaborationNodePropertyRevision,
	apply_collaborative_node_properties: applyCollaborativeNodeProperties,
	set_node_properties: setNodeProperties,
	set_node_parent: setNodeParent,
	rename_node: renameNode,
	delete_node: deleteNode,
	select_node: selectNode,
	get_selected_nodes: getSelectedNodes,

	// Meshes
	create_primitive_mesh: createPrimitiveMesh,
	get_mesh_geometry: getMeshGeometry,
	get_mesh_vertex_data: getMeshVertexData,
	get_mesh_topology: getMeshTopology,
	get_mesh_selection: getMeshSelection,
	set_mesh_geometry: setMeshGeometry,
	set_mesh_vertex_data: setMeshVertexData,
	set_mesh_selection: setMeshSelection,
	weld_mesh_vertices: weldMeshVertices,
	flip_mesh_normals: flipMeshNormals,
	extrude_mesh_faces: extrudeMeshFaces,
	inset_mesh_faces: insetMeshFaces,
	boolean_mesh: booleanMesh,
	bridge_mesh_edges: bridgeMeshEdges,
	bevel_mesh_edge: bevelMeshEdge,
	bevel_mesh_edges: bevelMeshEdges,
	set_mesh_uv_projection: setMeshUVProjection,
	unwrap_mesh_uvs: unwrapMeshUVs,
	subdivide_mesh: subdivideMesh,
	set_ground_heightmap: setGroundHeightmap,
	scatter_terrain_instances: scatterTerrainInstances,
	paint_terrain_details: paintTerrainDetails,
	paint_terrain_layer: paintTerrainLayer,
	// Animator controllers
	list_animator_controllers: listAnimatorControllers,
	create_animator_controller: createAnimatorController,
	get_animator_controller: getAnimatorController,
	get_animator_compiled_graph: getAnimatorCompiledGraph,
	get_animator_runtime_debug: getAnimatorRuntimeDebug,
	set_animator_controller: setAnimatorController,
	set_animator_subgraph: setAnimatorSubgraph,
	delete_animator_subgraph: deleteAnimatorSubgraph,
	set_animator_sub_state_machine: setAnimatorSubStateMachine,
	set_animator_entry_state: setAnimatorEntryState,
	set_animator_entry_transitions: setAnimatorEntryTransitions,
	set_animator_layer: setAnimatorLayer,
	set_animator_layer_blending: setAnimatorLayerBlending,
	set_animator_layer_ik_pass: setAnimatorLayerIKPass,
	set_animator_synchronized_layer_overrides: setAnimatorSynchronizedLayerOverrides,
	set_animator_layer_state: setAnimatorLayerState,
	set_animator_blend_tree: setAnimatorBlendTree,
	set_animator_state_mask: setAnimatorStateMask,
	set_animator_state_avatar_mask: setAnimatorStateAvatarMask,
	set_animator_state_behaviours: setAnimatorStateBehaviours,
	set_animator_state_graph_position: setAnimatorStateGraphPosition,
	set_animator_state: setAnimatorState,
	set_animator_transition: setAnimatorTransition,
	set_animator_parameter: setAnimatorParameter,
	set_animator_parameter_definition: setAnimatorParameterDefinition,
	set_animator_trigger: setAnimatorTrigger,
	reset_animator_trigger: resetAnimatorTrigger,
	set_animator_root_motion: setAnimatorRootMotion,
	open_animator_runtime_debugger: openAnimatorRuntimeDebugger,
	delete_animator_controller: deleteAnimatorController,
	list_input_action_maps: listInputActionMaps,
	create_input_action_map: createInputActionMap,
	set_input_action_map: setInputActionMap,
	set_input_action_binding: setInputActionBinding,
	simulate_input_touch: simulateInputTouch,

	// Physics constraints
	list_physics_constraints: listPhysicsConstraints,
	get_physics_simulation_state: getPhysicsSimulationState,
	validate_physics_scene: validatePhysicsScene,
	create_physics_constraint: createPhysicsConstraint,
	delete_physics_constraint: deletePhysicsConstraint,
	list_vehicles: listVehicles,
	create_vehicle: createVehicle,
	set_vehicle: setVehicle,
	delete_vehicle: deleteVehicle,
	set_vehicle_input: setVehicleInput,
	set_vehicle_wheels: setVehicleWheels,
	start_physics_contact_capture: startPhysicsContactCapture,
	get_physics_contact_capture: getPhysicsContactCapture,
	clear_physics_contact_capture: clearPhysicsContactCapture,
	stop_physics_contact_capture: stopPhysicsContactCapture,
	get_physics_contact_visualization: getPhysicsContactVisualization,
	set_physics_contact_visualization: setPhysicsContactVisualization,
	get_physics_simulation_control: getPhysicsSimulationControl,
	set_physics_simulation_paused: setPhysicsSimulationPaused,
	step_physics_simulation: stepPhysicsSimulation,

	// Rigging / IK
	get_skeleton_bones: getSkeletonBones,
	list_ik_controllers: listIKControllers,
	create_ik_controller: createIKController,
	set_ik_controller: setIKController,
	delete_ik_controller: deleteIKController,
	list_look_at_constraints: listLookAtConstraints,
	create_look_at_constraint: createLookAtConstraint,
	set_look_at_constraint: setLookAtConstraint,
	delete_look_at_constraint: deleteLookAtConstraint,
	list_rig_layers: listRigLayers,
	create_rig_layer: createRigLayer,
	set_rig_layer: setRigLayer,
	delete_rig_layer: deleteRigLayer,
	create_rig_constraint: createRigConstraint,
	set_rig_constraint: setRigConstraint,
	delete_rig_constraint: deleteRigConstraint,
	get_rig_constraint_graph: getRigConstraintGraph,
	set_rig_constraint_graph_layout: setRigConstraintGraphLayout,
	get_mesh_skin_weights: getMeshSkinWeights,
	set_mesh_skin_weights: setMeshSkinWeights,
	paint_mesh_skin_weights: paintMeshSkinWeights,
	optimize_mesh_skin_weights: optimizeMeshSkinWeights,
	mirror_mesh_skin_weights: mirrorMeshSkinWeights,
	list_sprite_ik_controllers: listSpriteIKControllers,
	create_sprite_ik_controller: createSpriteIKController,
	create_sprite_ik_rig: createSpriteIKRig,
	bake_sprite_ik_animation: bakeSpriteIKAnimation,
	set_sprite_ik_controller: setSpriteIKController,
	delete_sprite_ik_controller: deleteSpriteIKController,
	list_humanoid_avatars: listHumanoidAvatars,
	get_humanoid_avatar: getHumanoidAvatar,
	create_humanoid_avatar: createHumanoidAvatar,
	set_humanoid_avatar: setHumanoidAvatar,
	validate_humanoid_avatar: validateSceneHumanoidAvatar,
	delete_humanoid_avatar: deleteHumanoidAvatar,
	retarget_humanoid_animation: retargetHumanoidAnimation,
	inspect_humanoid_retarget: inspectHumanoidRetarget,
	set_humanoid_retarget_debug_visualization: setHumanoidRetargetDebugVisualization,
	set_humanoid_muscle_limits: setHumanoidMuscleLimits,
	get_humanoid_muscle_pose: getHumanoidMusclePose,
	set_humanoid_pose_preview: setHumanoidPosePreview,
	stop_humanoid_pose_preview: stopHumanoidPosePreview,
	list_humanoid_avatar_masks: listHumanoidAvatarMasks,
	create_humanoid_avatar_mask: createHumanoidAvatarMask,
	set_humanoid_avatar_mask: setHumanoidAvatarMask,
	delete_humanoid_avatar_mask: deleteHumanoidAvatarMask,

	// Cloth physics
	list_cloths: listCloths,
	create_cloth: createCloth,
	set_cloth: setCloth,
	delete_cloth: deleteCloth,

	// Physics 2D
	list_physics2d_bodies: listPhysics2D,
	get_physics2d_settings: getPhysics2DSettings,
	set_physics2d_settings: setPhysics2DSettings,
	list_physics2d_materials: listPhysics2DMaterials,
	create_physics2d_material: createPhysics2DMaterial,
	set_physics2d_material: setPhysics2DMaterial,
	delete_physics2d_material: deletePhysics2DMaterial,
	set_physics2d_body: setPhysics2DBody,
	generate_physics2d_polygon_collider: generatePhysics2DPolygonCollider,
	remove_physics2d_body: removePhysics2DBody,
	list_physics2d_joints: listPhysics2DJoints,
	create_physics2d_joint: createPhysics2DJoint,
	set_physics2d_joint: setPhysics2DJoint,
	delete_physics2d_joint: deletePhysics2DJoint,
	list_physics2d_effectors: listPhysics2DEffectors,
	create_physics2d_effector: createPhysics2DEffector,
	set_physics2d_effector: setPhysics2DEffector,
	delete_physics2d_effector: deletePhysics2DEffector,
	delete_input_action_map: deleteInputActionMap,
	generate_input_action_wrapper: generateInputActionWrapper,
	list_visual_script_graphs: listVisualScriptGraphs,
	create_visual_script_graph: createVisualScriptGraph,
	set_visual_script_graph: setVisualScriptGraph,
	set_visual_script_node_position: setVisualScriptNodePosition,
	run_visual_script_graph: runVisualScriptGraph,
	delete_visual_script_graph: deleteVisualScriptGraph,
	list_scene_tests: listSceneTests,
	list_performance_budgets: listPerformanceBudgets,
	create_scene_test: createSceneTest,
	create_performance_budget: createPerformanceBudget,
	set_scene_test: setSceneTest,
	set_performance_budget: setPerformanceBudget,
	run_scene_tests: runSceneTests,
	run_performance_budgets: runPerformanceBudgets,
	compare_visual_regression_images: compareVisualRegressionImages,
	delete_scene_test: deleteSceneTest,
	delete_performance_budget: deletePerformanceBudget,
	list_addressable_groups: listAddressableGroups,
	create_addressable_group: createAddressableGroup,
	assign_addressable_asset: assignAddressableAsset,
	remove_addressable_asset: removeAddressableAsset,
	build_addressable_catalog: buildAddressableCatalog,
	set_addressable_asset_labels: setAddressableAssetLabels,
	find_addressable_assets_by_labels: findAddressableAssetsByLabels,
	diff_addressable_catalogs: diffAddressableCatalogs,
	list_localization_tables: listLocalizationTables,
	create_localization_table: createLocalizationTable,
	delete_localization_table: deleteLocalizationTable,
	set_localization_entry: setLocalizationEntry,
	delete_localization_entry: deleteLocalizationEntry,
	resolve_localization_entry: resolveLocalizationEntry,
	pseudo_localize_entry: pseudoLocalizeEntry,
	validate_localization: validateLocalization,
	list_behavior_trees: listBehaviorTrees,
	create_behavior_tree: createBehaviorTree,
	set_behavior_tree: setBehaviorTree,
	run_behavior_tree: runBehaviorTree,
	delete_behavior_tree: deleteBehaviorTree,
	list_project_packages: listProjectPackages,
	modify_project_package: modifyProjectPackage,
	get_project_source_control_status: getProjectSourceControlStatus,
	get_project_source_control_history: getProjectSourceControlHistory,
	get_project_source_control_diff: getProjectSourceControlDiff,
	stage_project_source_control_paths: stageProjectSourceControlPaths,
	unstage_project_source_control_paths: unstageProjectSourceControlPaths,
	commit_project_source_control: commitProjectSourceControl,
	push_project_source_control: pushProjectSourceControl,
	list_project_source_control_refs: listProjectSourceControlRefs,
	fetch_project_source_control: fetchProjectSourceControl,
	pull_project_source_control: pullProjectSourceControl,
	create_project_source_control_branch: createProjectSourceControlBranch,
	switch_project_source_control_branch: switchProjectSourceControlBranch,
	delete_project_source_control_branch: deleteProjectSourceControlBranch,
	create_project_source_control_tag: createProjectSourceControlTag,
	delete_project_source_control_tag: deleteProjectSourceControlTag,
	preview_project_source_control_integration: previewProjectSourceControlIntegration,
	get_project_source_control_integration_state: getProjectSourceControlIntegrationState,
	start_project_source_control_merge: startProjectSourceControlMerge,
	start_project_source_control_rebase: startProjectSourceControlRebase,
	resolve_project_source_control_conflict: resolveProjectSourceControlConflict,
	continue_project_source_control_integration: continueProjectSourceControlIntegration,
	abort_project_source_control_integration: abortProjectSourceControlIntegration,
	inspect_project_source_control_remote_refs: inspectProjectSourceControlRemoteRefs,
	publish_project_source_control_remote_branch: publishProjectSourceControlRemoteBranch,
	delete_project_source_control_remote_branch: deleteProjectSourceControlRemoteBranch,
	publish_project_source_control_remote_tag: publishProjectSourceControlRemoteTag,
	delete_project_source_control_remote_tag: deleteProjectSourceControlRemoteTag,
	inspect_project_source_control_conflict_details: inspectProjectSourceControlConflictDetails,
	apply_project_source_control_text_resolution: applyProjectSourceControlTextResolution,
	inspect_project_source_control_authentication: inspectProjectSourceControlAuthentication,
	inspect_project_source_control_image_conflict: inspectProjectSourceControlImageConflict,
	get_project_source_control_review_provider: getProjectSourceControlReviewProvider,
	set_project_source_control_review_provider: setProjectSourceControlReviewProvider,
	list_project_source_control_reviews: listProjectSourceControlReviews,
	get_project_source_control_review: getProjectSourceControlReview,
	get_project_source_control_review_metadata: getProjectSourceControlReviewMetadata,
	set_project_source_control_review_metadata: setProjectSourceControlReviewMetadata,
	list_project_source_control_review_checks: listProjectSourceControlReviewChecks,
	rerun_project_source_control_review_checks: rerunProjectSourceControlReviewChecks,
	create_project_source_control_review: createProjectSourceControlReview,
	submit_project_source_control_review: submitProjectSourceControlReview,
	merge_project_source_control_review: mergeProjectSourceControlReview,
	list_project_asset_locks: listProjectAssetLocks,
	acquire_project_asset_lock: acquireProjectAssetLock,
	refresh_project_asset_lock: refreshProjectAssetLock,
	release_project_asset_lock: releaseProjectAssetLock,
	compare_project_scene_assets: compareProjectSceneAssets,
	merge_project_scene_assets: mergeProjectSceneAssets,
	list_project_semantic_merge_rules: listProjectSemanticMergeRules,
	create_project_semantic_merge_rule: createProjectSemanticMergeRule,
	set_project_semantic_merge_rule: setProjectSemanticMergeRule,
	delete_project_semantic_merge_rule: deleteProjectSemanticMergeRule,
	get_project_collaboration_status: getProjectCollaborationStatus,
	configure_project_collaboration: configureProjectCollaboration,
	list_project_collaboration_members: listProjectCollaborationMembers,
	create_project_collaboration_member: createProjectCollaborationMember,
	set_project_collaboration_member: setProjectCollaborationMember,
	delete_project_collaboration_member: deleteProjectCollaborationMember,
	join_project_collaboration_session: joinProjectCollaborationSession,
	heartbeat_project_collaboration_session: heartbeatProjectCollaborationSession,
	leave_project_collaboration_session: leaveProjectCollaborationSession,
	list_project_collaboration_presence: listProjectCollaborationPresence,
	generate_remote_collaboration_tls_certificate: generateRemoteCollaborationTlsCertificate,
	inspect_remote_collaboration_tls_certificate: inspectRemoteCollaborationTlsCertificate,
	get_remote_collaboration_discovery: getRemoteCollaborationDiscovery,
	set_remote_collaboration_discovery: setRemoteCollaborationDiscovery,
	discover_remote_collaboration_projects: discoverRemoteCollaborationProjects,
	get_remote_collaboration_relay: getRemoteCollaborationRelay,
	set_remote_collaboration_relay: setRemoteCollaborationRelay,
	reconnect_remote_collaboration_relay: reconnectRemoteCollaborationRelay,
	get_remote_collaboration_gateway: getRemoteCollaborationGateway,
	set_remote_collaboration_gateway: setRemoteCollaborationGateway,
	set_remote_collaboration_event_history: setRemoteCollaborationEventHistory,
	clear_remote_collaboration_event_history: clearRemoteCollaborationEventHistory,
	get_project_asset_lock_federation: getProjectAssetLockFederation,
	list_remote_collaboration_events: listRemoteCollaborationEvents,
	list_project_changelists: listProjectChangelists,
	create_project_changelist: createProjectChangelist,
	set_project_changelist: setProjectChangelist,
	set_project_changelist_files: setProjectChangelistFiles,
	delete_project_changelist: deleteProjectChangelist,
	list_sorting_layers: listSortingLayers,
	create_sorting_layer: createSortingLayer,
	set_node_sorting_layer: setNodeSortingLayer,
	get_xr_configuration: getXRConfiguration,
	set_xr_configuration: setXRConfiguration,
	list_virtual_cameras: listVirtualCameras,
	create_virtual_camera: createVirtualCamera,
	activate_virtual_camera: activateVirtualCamera,
	blend_virtual_camera: blendVirtualCamera,
	activate_highest_priority_virtual_camera: activateHighestPriorityVirtualCamera,
	delete_virtual_camera: deleteVirtualCamera,
	set_virtual_camera_dolly: setVirtualCameraDolly,
	list_camera_target_groups: listCameraTargetGroups,
	set_camera_target_group: setCameraTargetGroup,
	set_virtual_camera_target_groups: setVirtualCameraTargetGroups,
	delete_camera_target_group: deleteCameraTargetGroup,
	list_camera_impulse_sources: listCameraImpulseSources,
	set_camera_impulse_source: setCameraImpulseSource,
	fire_camera_impulse: fireCameraImpulse,
	delete_camera_impulse_source: deleteCameraImpulseSource,
	list_terrain_streaming_groups: listTerrainStreamingGroups,
	set_terrain_streaming_group: setTerrainStreamingGroup,
	delete_terrain_streaming_group: deleteTerrainStreamingGroup,
	get_particle_collision_planes: getParticleCollisionPlanes,
	set_particle_collision_planes: setParticleCollisionPlanes,
	get_particle_collision_spheres: getParticleCollisionSpheres,
	set_particle_collision_spheres: setParticleCollisionSpheres,
	// Splines
	list_splines: listSplines,
	create_spline: createSpline,
	get_spline: getSpline,
	set_spline: setSpline,
	save_spline_asset: saveSplineAsset,
	list_spline_assets: listSplineAssets,
	instantiate_spline_asset: instantiateSplineAsset,
	project_spline_to_terrain: projectSplineToTerrain,
	evaluate_spline: evaluateSpline,
	list_spline_followers: listSplineFollowers,
	set_spline_follower: setSplineFollower,
	delete_spline_follower: deleteSplineFollower,
	get_terrain: getTerrain,
	sculpt_terrain: sculptTerrain,
	carve_terrain_hole: carveTerrainHole,
	create_decal: createDecal,
	get_decal: getDecal,
	set_decal: setDecal,
	list_skeletons: listSkeletons,
	set_skeleton: setSkeleton,
	get_mesh_morph_targets: getMeshMorphTargets,
	set_mesh_morph_targets: setMeshMorphTargets,
	create_instance: createInstance,
	clone_mesh: cloneMesh,
	get_mesh_lods: getMeshLODs,
	set_mesh_lods: setMeshLODs,
	get_mesh_collision: getMeshCollision,
	set_mesh_collision: setMeshCollision,
	set_mesh_material: setMeshMaterial,
	set_mesh_visibility: setMeshVisibility,
	set_mesh_physics: setMeshPhysics,
	get_mesh_bounding_info: getMeshBoundingInfo,

	// Lights & shadows
	create_light: createLight,
	get_light: getLight,
	set_light_properties: setLightProperties,
	list_lighting_scenarios: listLightingScenarios,
	create_lighting_scenario: createLightingScenario,
	apply_lighting_scenario: applyLightingScenario,
	blend_lighting_scenario: blendLightingScenario,
	delete_lighting_scenario: deleteLightingScenario,
	set_ibl_shadows: setIblShadows,
	list_reflection_probes: listReflectionProbes,
	create_reflection_probe: createReflectionProbe,
	set_reflection_probe: setReflectionProbe,
	delete_reflection_probe: deleteReflectionProbe,
	set_light_shadows: setLightShadows,
	remove_light_shadows: removeLightShadows,
	create_clustered_light_container: createClusteredLightContainer,
	add_light_to_clustered_container: addLightToClusteredContainer,
	remove_light_from_clustered_container: removeLightFromClusteredContainer,

	// Cameras
	create_camera: createCamera,
	get_camera: getCamera,
	set_camera_properties: setCameraProperties,
	set_active_camera: setActiveCamera,

	// Camera post-processes / rendering pipelines
	get_camera_post_processes: getCameraPostProcesses,
	set_camera_post_process: setCameraPostProcess,
	list_rendering_profiles: listRenderingProfiles,
	create_rendering_profile: createRenderingProfile,
	set_rendering_profile: setRenderingProfile,
	apply_rendering_profile: applyRenderingProfile,
	delete_rendering_profile: deleteRenderingProfile,
	list_rendering_volumes: listRenderingVolumes,
	create_rendering_volume: createRenderingVolume,
	set_rendering_volume: setRenderingVolume,
	evaluate_rendering_volumes: evaluateRenderingVolumes,
	delete_rendering_volume: deleteRenderingVolume,
	list_custom_render_passes: listCustomRenderPasses,
	create_custom_render_pass: createCustomRenderPass,
	set_custom_render_pass: setCustomRenderPass,
	delete_custom_render_pass: deleteCustomRenderPass,
	evaluate_custom_render_pass_graph: evaluateCustomRenderPassGraph,
	get_custom_render_pass_diagnostics: getCustomRenderPassGraphDiagnostics,
	get_custom_render_pass_schedule: getCustomRenderPassGraphSchedule,
	set_custom_render_pass_gpu_profiling: setCustomRenderPassGpuProfiling,
	get_custom_render_pass_gpu_profile: getCustomRenderPassGpuProfiling,
	set_custom_compute_storage_buffer_data: setCustomComputeStorageBufferData,
	set_custom_compute_uniform_buffer_values: setCustomComputeUniformBufferValues,
	read_custom_compute_storage_buffer: readCustomComputeStorageBuffer,
	get_custom_compute_node_graph: getCustomComputeNodeGraph,
	initialize_custom_compute_node_graph: initializeCustomComputeNodeGraph,
	set_custom_compute_node_graph: setCustomComputeNodeGraph,
	add_custom_compute_node: addCustomComputeNode,
	set_custom_compute_node: setCustomComputeNode,
	delete_custom_compute_node: deleteCustomComputeNode,
	connect_custom_compute_nodes: connectCustomComputeNodes,
	disconnect_custom_compute_nodes: disconnectCustomComputeNodes,
	compile_custom_compute_node_graph: compileCustomComputeNodeGraph,
	save_custom_compute_subgraph: saveCustomComputeSubgraph,
	list_custom_compute_subgraphs: listCustomComputeSubgraphs,
	get_custom_compute_subgraph: getCustomComputeSubgraph,
	get_custom_compute_subgraph_migration: getCustomComputeSubgraphMigration,
	migrate_custom_compute_subgraph: migrateCustomComputeSubgraph,
	insert_custom_compute_subgraph: insertCustomComputeSubgraph,
	delete_custom_compute_subgraph: deleteCustomComputeSubgraph,
	list_custom_compute_subgraph_instances: listCustomComputeSubgraphInstances,
	set_custom_compute_subgraph_instance: setCustomComputeSubgraphInstance,
	refresh_custom_compute_subgraph_instance: refreshCustomComputeSubgraphInstance,
	delete_custom_compute_subgraph_instance: deleteCustomComputeSubgraphInstance,
	get_custom_compute_subgraph_diagnostics: getCustomComputeSubgraphDiagnostics,
	preview_custom_compute_node_graph: previewCustomComputeNodeGraph,
	debug_custom_compute_node_graph: debugCustomComputeNodeGraph,
	get_custom_compute_node_profile: getCustomComputeNodeProfile,
	get_custom_compute_texture_node_previews: getCustomComputeTextureNodePreviews,
	capture_custom_render_pass_output: captureCustomRenderPassOutput,

	// Materials & textures
	list_materials: listMaterials,
	list_material_types: listMaterialTypes,
	create_material: createMaterial,
	create_material_variant: createMaterialVariant,
	get_material_variant: getMaterialVariant,
	rebase_material_variant: rebaseMaterialVariant,
	list_material_presets: listMaterialPresets,
	create_material_preset: createMaterialPreset,
	apply_material_preset: applyMaterialPreset,
	delete_material_preset: deleteMaterialPreset,
	delete_material: deleteMaterial,
	set_material_properties: setMaterialProperties,
	get_material_lightmap: getMaterialLightmap,
	set_material_lightmap: setMaterialLightmap,
	get_node_material_graph: getNodeMaterialGraph,
	list_node_material_custom_blocks: listNodeMaterialCustomBlocks,
	add_node_material_custom_block: addNodeMaterialCustomBlock,
	delete_node_material_custom_block: deleteNodeMaterialCustomBlock,
	get_node_material_blackboard: getNodeMaterialBlackboard,
	get_node_material_subgraph: getNodeMaterialSubgraph,
	list_node_material_variants: listNodeMaterialVariants,
	set_node_material_variant: setNodeMaterialVariant,
	apply_node_material_variant: applyNodeMaterialVariant,
	delete_node_material_variant: deleteNodeMaterialVariant,
	validate_node_material_graph: validateNodeMaterialGraph,
	strip_node_material_unused_blocks: stripNodeMaterialUnusedBlocks,
	set_node_material_inputs: setNodeMaterialInputs,
	set_node_material_blackboard: setNodeMaterialBlackboard,
	set_node_material_blackboard_values: setNodeMaterialBlackboardValues,
	replace_node_material_graph: replaceNodeMaterialGraph,
	save_node_material_subgraph: saveNodeMaterialSubgraph,
	apply_node_material_subgraph: applyNodeMaterialSubgraph,
	assign_texture_to_material: assignTextureToMaterial,
	set_environment_texture: setEnvironmentTexture,

	// Assets browser
	list_assets: listAssets,
	get_asset_watch_status: getAssetWatchStatus,
	refresh_watched_assets: refreshWatchedAssets,
	get_asset_details: getAssetDetails,
	list_asset_dependency_scanners: listDependencyScannerTypes,
	get_asset_dependencies: getAssetDependencies,
	inspect_asset_move: inspectAssetMovePlan,
	apply_asset_move: applyAssetMovePlan,
	get_asset_dependency_graph: inspectAssetDependencyGraph,
	export_asset_dependency_graph: exportAssetDependencyGraph,
	open_asset_dependency_graph: openAssetDependencyGraphView,
	get_asset_dependency_diagnostics: inspectAssetDependencyDiagnostics,
	rebuild_asset_dependency_index: rebuildAssetDependencyIndex,
	get_asset_by_guid: getAssetByGuid,
	get_asset_registry_status: getPersistentAssetRegistryStatus,
	get_asset_indexing_status: getBackgroundAssetIndexingStatus,
	start_asset_indexing: startBackgroundAssetIndexing,
	cancel_asset_indexing: cancelBackgroundAssetIndexing,
	query_asset_registry: queryPersistentAssetRegistry,
	rebuild_asset_registry: rebuildPersistentAssetRegistry,
	refresh_asset_registry_paths: refreshPersistentAssetRegistryPaths,
	set_asset_metadata: setAssetMetadata,
	set_asset_organization: setAssetOrganization,
	get_asset_import_status: getAssetImportStatus,
	refresh_asset_import_states: refreshAssetImportStates,
	list_asset_import_diagnostics: listAssetImportDiagnostics,
	list_asset_importer_presets: listAssetImporterPresets,
	set_asset_importer_preset: setAssetImporterPreset,
	list_asset_importer_types: listAssetImporterTypes,
	get_asset_importer: getAssetImporter,
	open_asset_inspector: openAssetInspector,
	validate_asset_importer_settings: validateAssetImporterSettings,
	set_asset_importer_settings: setAssetImporterSettings,
	set_model_rig_optimization: setModelRigOptimization,
	get_model_animation_clips: getModelAnimationClips,
	set_model_animation_clips: setModelAnimationClips,
	get_model_material_remaps: getModelMaterialRemaps,
	set_model_material_remaps: setModelMaterialRemaps,
	get_model_material_search: getModelMaterialSearch,
	set_model_material_search: setModelMaterialSearch,
	get_model_platform_overrides: getModelPlatformOverrides,
	set_model_platform_overrides: setModelPlatformOverrides,
	inspect_model_material_extraction: inspectModelMaterialExtraction,
	extract_model_materials: extractModelMaterials,
	inspect_model_texture_extraction: inspectModelTextureExtraction,
	extract_model_textures: extractModelTextures,
	get_model_generated_lods: getModelGeneratedLods,
	set_model_generated_lods: setModelGeneratedLods,
	get_model_authored_lods: getModelAuthoredLods,
	set_model_authored_lods: setModelAuthoredLods,
	get_texture_importer_result: getTextureImporterResult,
	apply_texture_importer: applyTextureImporter,
	get_audio_importer_result: getAudioImporterResult,
	apply_audio_importer: applyAudioImporter,
	get_video_importer_result: getVideoImporterResult,
	apply_video_importer: applyVideoImporter,
	get_font_importer_result: getFontImporterResult,
	apply_font_importer: applyFontImporter,
	get_material_importer_result: getMaterialImporterResult,
	apply_material_importer: applyMaterialImporter,
	get_model_importer_result: getModelImporterResult,
	apply_model_importer: applyModelImporter,
	get_animation_importer_result: getAnimationImporterResult,
	apply_animation_importer: applyAnimationImporter,
	get_animator_controller_asset_import: getAnimatorControllerAssetImport,
	import_animator_controller_asset: importAnimatorControllerAsset,
	apply_asset_importer_preset: applyAssetImporterPreset,
	delete_asset_importer_preset: deleteAssetImporterPreset,
	reimport_asset: reimportAsset,
	get_asset_preview: getAssetPreview,
	convert_image_asset: convertImageAsset,
	import_asset: importAsset,
	instantiate_mesh_asset: instantiateMeshAsset,
	create_asset_folder: createAssetFolder,
	move_asset: moveAsset,
	delete_asset: deleteAsset,

	// Particle systems
	list_particle_assets: listParticleAssets,
	list_particle_systems: listParticleSystems,
	list_node_particle_systems: listNodeParticleSystems,
	instantiate_particle_system: instantiateParticleSystem,
	set_particle_system_properties: setParticleSystemProperties,
	set_particle_system_playing: setParticleSystemPlaying,
	validate_particle_system: validateParticleSystem,
	get_particle_attractors: getParticleAttractors,
	set_particle_attractors: setParticleAttractors,
	list_vfx_budget_profiles: listVfxBudgetProfiles,
	create_vfx_budget_profile: createVfxBudgetProfile,
	set_vfx_budget_profile: setVfxBudgetProfile,
	apply_vfx_budget_profile: applyVfxBudgetProfile,
	delete_vfx_budget_profile: deleteVfxBudgetProfile,
	get_particle_vector_fields: getParticleVectorFields,
	set_particle_vector_fields: setParticleVectorFields,
	get_particle_texture_vector_fields: getParticleTextureVectorFields,
	create_particle_texture_vector_field: createParticleTextureVectorField,
	set_particle_texture_vector_fields: setParticleTextureVectorFields,
	get_particle_proximity_events: getParticleProximityEvents,
	set_particle_proximity_events: setParticleProximityEvents,
	get_particle_events: getParticleEvents,
	set_particle_events: setParticleEvents,
	trigger_particle_event: triggerParticleEvent,
	create_vfx_trail: createVfxTrail,
	list_vfx_trails: listVfxTrails,
	get_vfx_trail: getVfxTrail,
	set_vfx_trail: setVfxTrail,
	delete_vfx_trail: deleteVfxTrail,
	get_node_particle_system_graph: getNodeParticleSystemGraph,
	replace_node_particle_system_graph: replaceNodeParticleSystemGraph,

	// Sprites
	list_sprite_managers: listSpriteManagers,
	create_sprite_manager: createSpriteManager,
	set_sprite_manager: setSpriteManager,
	pack_sprite_atlas: packSpriteAtlas,
	slice_sprite_sheet: sliceSpriteSheet,
	list_sprites: listSprites,
	create_sprite: createSprite,
	set_sprite: setSprite,
	play_sprite_animation: playSpriteAnimation,
	list_sprite_maps: listSpriteMaps,
	create_sprite_map: createSpriteMap,
	set_sprite_map: setSpriteMap,
	set_sprite_map_rule_tiles: setSpriteMapRuleTiles,
	resolve_sprite_map_rule_tiles: resolveSpriteMapRuleTiles,
	set_sprite_map_tiles: setSpriteMapTiles,
	list_tile_palettes: listTilePalettes,
	create_tile_palette: createTilePalette,
	set_tile_palette: setTilePalette,
	paint_tile_palette: paintTilePalette,
	delete_tile_palette: deleteTilePalette,
	list_animated_tiles: listAnimatedTiles,
	create_animated_tile: createAnimatedTile,
	set_animated_tile: setAnimatedTile,
	delete_animated_tile: deleteAnimatedTile,
	get_tile_collider_generator: getTileColliderGenerator,
	generate_tile_colliders: generateTileColliders,
	refresh_tile_colliders: refreshTileColliders,
	clear_tile_collider_generator: clearTileColliderGenerator,

	// GUI
	list_guis: listGUIs,
	create_gui_asset: createGUIAsset,
	get_gui_asset: getGUIAsset,
	instantiate_gui_asset: instantiateGUIAsset,
	get_gui_content: getGUIContent,
	set_gui_content: setGUIContent,
	save_gui_asset: saveGUIAsset,
	validate_gui_accessibility: validateGUIAccessibility,

	// Cinematics
	list_cinematics: listCinematics,
	get_cinematic: getCinematic,
	create_cinematic: createCinematic,
	save_cinematic: saveCinematic,
	play_cinematic: playCinematic,

	// Navigation
	list_navmeshes: listNavMeshes,
	get_navmesh: getNavMesh,
	create_navmesh: createNavMesh,
	set_navmesh_configuration: setNavMeshConfiguration,
	rebuild_navmesh: rebuildNavMesh,
	get_navmesh_data: getNavMeshData,
	compute_navmesh_path: computeNavMeshPath,
	list_nav_agents: listNavAgents,
	create_nav_agent: createNavAgent,
	set_nav_agent_destination: setNavAgentDestination,
	set_nav_agent: setNavAgent,
	delete_nav_agent: deleteNavAgent,
	list_navmesh_links: listNavMeshLinks,
	list_navmesh_areas: listNavMeshAreas,
	create_navmesh_link: createNavMeshLink,
	set_navmesh_link: setNavMeshLink,
	set_navmesh_areas: setNavMeshAreas,
	delete_navmesh_link: deleteNavMeshLink,
	start_nav_agent: startNavAgent,
	stop_nav_agent: stopNavAgent,

	// Ragdolls
	list_ragdolls: listRagdolls,
	get_ragdoll: getRagdoll,
	save_ragdoll: saveRagdoll,

	// Project settings
	get_project_preferences: getProjectPreferences,
	list_installed_external_editors: listInstalledExternalEditors,
	set_project_preferences: setProjectPreferences,
	list_project_templates: listProjectTemplates,
	open_project_file_in_external_editor: openProjectFileInExternalEditor,

	// Prefabs
	list_prefabs: listPrefabs,
	get_prefab: getPrefab,
	create_prefab: createPrefab,
	create_prefab_variant: createPrefabVariant,
	inspect_prefab_variant_rebase: inspectPrefabVariantRebase,
	inspect_prefab_asset_node_property: inspectPrefabAssetNodeProperty,
	inspect_prefab_variant_structure: inspectPrefabVariantStructure,
	inspect_prefab_variant_components: inspectPrefabVariantComponents,
	rebase_prefab_variant: rebasePrefabVariant,
	set_prefab_asset_node_properties: setPrefabAssetNodeProperties,
	set_prefab_asset_node_property: setPrefabAssetNodeProperty,
	set_prefab_variant_overrides: setPrefabVariantOverrides,
	set_prefab_variant_structure: setPrefabVariantStructure,
	set_prefab_variant_components: setPrefabVariantComponents,
	inspect_prefab_instance_links: inspectPrefabInstanceLinks,
	inspect_prefab_instance_structure: inspectPrefabInstanceStructure,
	capture_prefab_instance_structure: capturePrefabInstanceStructure,
	compare_prefab_instances: comparePrefabInstances,
	apply_prefab_instance_boundary: applyPrefabInstanceBoundary,
	revert_prefab_instance_boundary: revertPrefabInstanceBoundary,
	unpack_prefab_instance: unpackPrefabInstance,
	promote_prefab_instance_boundary_overrides: promotePrefabInstanceBoundaryOverrides,
	apply_prefab_instance_root: applyPrefabInstanceRoot,
	revert_prefab_instance_root: revertPrefabInstanceRoot,
	apply_prefab_instance_node: applyPrefabInstanceNode,
	revert_prefab_instance_node: revertPrefabInstanceNode,
	instantiate_prefab: instantiatePrefab,

	// Export
	get_generate_options: getGenerateOptions,
	get_export_report: getExportReport,
	export_active_scene: exportActiveScene,
	list_build_profiles: listBuildProfiles,
	list_build_reports: listBuildReports,
	create_build_profile: createBuildProfile,
	set_build_profile: setBuildProfile,
	delete_build_profile: deleteBuildProfile,
	run_build_profile: runBuildProfile,
	get_build_profile_environment: getBuildProfileEnvironment,
	validate_build_profile: validateBuildProfile,
	build_build_profile: buildBuildProfile,
	generate_pwa_manifest: generatePwaManifest,
	generate_pwa_service_worker: generatePwaServiceWorker,
	install_pwa_service_worker_registration: installPwaServiceWorkerRegistration,

	// Editor controls
	get_gizmo_settings: getGizmoSettings,
	set_gizmo_settings: setGizmoSettings,
	list_editor_tabs: listEditorTabs,
	select_editor_tab: selectEditorTab,
	write_editor_console: writeEditorConsole,
	clear_editor_console: clearEditorConsole,
	run_editor_terminal_command: runEditorTerminalCommand,

	// Sounds
	list_sound_assets: listSoundAssets,
	create_sound: createSound,
	get_sound: getSound,
	set_sound_properties: setSoundProperties,
	set_sound_playing: setSoundPlaying,
	list_audio_buses: listAudioBuses,
	list_audio_runtime_diagnostics: listAudioRuntimeDiagnostics,
	create_audio_bus: createAudioBus,
	set_audio_bus: setAudioBus,
	delete_audio_bus: deleteAudioBus,
	list_audio_mixer_snapshots: listAudioMixerSnapshots,
	create_audio_mixer_snapshot: createAudioMixerSnapshot,
	apply_audio_mixer_snapshot: applyAudioMixerSnapshot,
	assign_sound_node_to_audio_bus: assignSoundNodeToAudioBus,
	delete_audio_mixer_snapshot: deleteAudioMixerSnapshot,

	// Video players
	list_video_players: listVideoPlayers,
	create_video_player: createVideoPlayer,
	set_video_player: setVideoPlayer,
	control_video_player: controlVideoPlayer,
	delete_video_player: deleteVideoPlayer,

	// Animations
	list_animation_groups: listAnimationGroups,
	play_animation_group: playAnimationGroup,
	stop_animation_group: stopAnimationGroup,
	create_animation: createAnimation,
	get_animation_group: getAnimationGroup,
	get_animation_window: getAnimationWindow,
	edit_animation_window_keys: editAnimationWindowKeys,
	open_animation_window: openAnimationWindow,
	list_animation_events: listAnimationEvents,
	set_animation_events: setAnimationEvents,
	set_animation_curve_keys: setAnimationCurveKeys,
	set_animation_curve_component_keys: setAnimationCurveComponentKeys,
	set_animation_curve_tangents: setAnimationCurveTangents,
	auto_smooth_animation_curve_tangents: autoSmoothAnimationCurveTangents,
	set_animation_keys: setAnimationKeys,
	sample_animation_curve: sampleAnimationCurve,
	export_animation_group: exportAnimationGroup,
	import_animation_group: importAnimationGroup,
	delete_animation_group: deleteAnimationGroup,

	// Marketplace
	open_marketplace: openMarketplaceAndSelectAsset,
	search_marketplace: openMarketplaceAndSearch,
	download_marketplace_asset: downloadMarketplaceAsset,

	// Scripts
	list_scripts: listScripts,
	list_script_templates: listScriptTemplates,
	list_custom_script_templates: listCustomScriptTemplates,
	set_custom_script_template: setCustomScriptTemplate,
	create_script: createScript,
	read_script: readScript,
	write_script: writeScript,
	rename_script: renameScript,
	delete_script: deleteScript,
	validate_script: validateScript,
	get_script_semantic_diagnostics: getScriptSemanticDiagnostics,
	get_project_script_semantic_diagnostics: getProjectScriptSemanticDiagnostics,
	get_script_runtime_diagnostics: getScriptRuntimeDiagnostics,
	get_script_exported_fields: getScriptExportedFields,
	attach_script: attachScript,
	list_attached_scripts: listAttachedScripts,
	set_script_exported_value: setScriptExportedValue,
	set_attached_script_execution_order: setAttachedScriptExecutionOrder,
	list_scene_script_execution_orders: listProjectScriptExecutionOrders,
	set_scene_script_execution_order: setProjectScriptExecutionOrder,
	list_project_script_execution_orders: listProjectWideScriptExecutionOrders,
	set_project_script_execution_order: setProjectWideScriptExecutionOrder,
	detach_script: detachScript,

	// Agent automation scripts (.js run in the editor via main(editor))
	get_editor_api: getEditorApi,
	write_agent_script: writeAgentScript,
	run_agent_script: runAgentScript,
	list_agent_scripts: listAgentScripts,

	// Verification & utility
	get_screenshot: getScreenshot,
	capture_visual_regression_baseline: captureVisualRegressionBaseline,
	focus_node: focusNode,
	run_project: runProject,
};

// Batch endpoint reuses the same handlers from the map above.
MCPEndpoints.execute_batch = createBatchHandler(MCPEndpoints);

/**
 * Initializes the editor MCP HTTP server.
 * Resilient: if the port is already in use (e.g. a second editor window), the error is caught
 * and logged in the editor console instead of crashing the application.
 * @param editor defines the reference to the editor.
 */
export function initializeMcpServer(editor: Editor): void {
	void initializeRemoteCollaborationGateway(editor, MCPEndpoints).catch((error) => {
		editor.layout.console.error(`Remote collaboration gateway failed to initialize: ${error instanceof Error ? error.message : String(error)}`);
	});
	const server = createServer(async (req, res) => {
		let data: IEditorMCPDataType;
		try {
			data = await new Promise<IEditorMCPDataType>((resolve, reject) => {
				let body = "";

				req.on("data", (chunk) => (body += chunk));
				req.on("end", () => resolve(JSON.parse(body)));
				req.on("error", reject);
			});
		} catch (e) {
			res.writeHead(400);
			res.end(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }));
			return;
		}

		const action = MCPEndpoints[data.endpoint];

		if (!action) {
			res.writeHead(404);
			res.end(JSON.stringify({ error: `Unknown endpoint: ${data.endpoint}` }));
			return;
		}

		try {
			await authorizeProjectCollaborationRequest(data.endpoint, data, { editor });
			const result = await action(editor.layout.preview.scene, data, { editor });
			await publishRemoteCollaborationOperation(data.endpoint, true, data.collaborationToken, { editor }, "Editor action completed.");

			res.writeHead(200);
			res.end(JSON.stringify(result ?? null));
		} catch (e) {
			await publishRemoteCollaborationOperation(data.endpoint, false, data.collaborationToken, { editor }, e instanceof Error ? e.message : String(e)).catch(() => undefined);
			res.writeHead(500);
			res.end(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }));
		}
	});

	server.on("error", (e) => {
		editor.layout.console.error(`MCP Server failed to start: ${e instanceof Error ? e.message : String(e)}`);
	});

	server.listen(MCPServerPort, "127.0.0.1", () => {
		editor.layout.console.log(`MCP Server is listening on port ${MCPServerPort}`);
	});
}
